(()=>{'use strict';
const SAVE_KEY='mist-taiwan-rpg-save-v3',OLD_SAVE_KEY='mist-taiwan-rpg-save-v2';
const backgrounds={
student:{label:'學生',passive:'求知',stats:{insight:2,knowledge:2,composure:0,rapport:0},items:['student_id','notebook']},
worker:{label:'工人',passive:'同袍',stats:{insight:0,knowledge:0,composure:2,rapport:2},items:['work_gloves','meal_ticket']},
clerk:{label:'公務員',passive:'熟悉體制',stats:{insight:0,knowledge:1,composure:1,rapport:2},items:['fountain_pen','document_bag']},
reporter:{label:'記者',passive:'新聞嗅覺',stats:{insight:2,knowledge:1,composure:0,rapport:1},items:['reporter_notes','camera']},
teacher:{label:'教師',passive:'為人師表',stats:{insight:0,knowledge:2,composure:0,rapport:2},items:['teacher_id','old_dictionary']},
merchant:{label:'商人',passive:'生意人',stats:{insight:0,knowledge:0,composure:1,rapport:3},items:['ledger','coin_purse']},
veteran:{label:'退伍軍人',passive:'戰地經驗',stats:{insight:1,knowledge:0,composure:3,rapport:0},items:['army_bag','veteran_card']},
homemaker:{label:'持家者',passive:'街坊消息',stats:{insight:1,knowledge:0,composure:1,rapport:2},items:['household_book','cloth_bag']}
};
const items={student_id:{name:'學生證',desc:'證明學生身分；在校園與書店場合可能派上用場。',type:'tool'},work_gloves:{name:'舊工作手套',desc:'粗厚耐用，帶著工廠生活留下的痕跡。',type:'equipment',slot:'hand',bonus:{composure:1}},fountain_pen:{name:'鋼筆',desc:'一支體面的鋼筆，適合記錄與公務場合。',type:'equipment',slot:'hand',bonus:{rapport:1}},document_bag:{name:'公文袋',desc:'習慣用來整理文件的硬紙袋。',type:'tool'},reporter_notes:{name:'記者筆記',desc:'頁角密密寫著日期、姓名與待查事項。',type:'equipment',slot:'pocket',bonus:{insight:1}},camera:{name:'底片相機',desc:'不輕便，但能在特定事件留下影像證據。',type:'tool'},teacher_id:{name:'教職證明',desc:'證明你的教師身分。',type:'tool'},ledger:{name:'商用帳本',desc:'熟悉的帳目格式能幫助你看出數字中的異常。',type:'tool'},coin_purse:{name:'零錢包',desc:'做生意養成隨身準備零錢的習慣。',type:'tool'},army_bag:{name:'舊軍用背包',desc:'退伍後仍留下的耐用背包。',type:'equipment',slot:'bag',bonus:{composure:1}},veteran_card:{name:'退伍證明',desc:'一張收得很平整的退伍證明。',type:'tool'},household_book:{name:'家庭帳簿',desc:'柴米油鹽與每月支出都記得清楚。',type:'tool'},cloth_bag:{name:'布提袋',desc:'買菜、跑腿與裝雜物都很實用。',type:'equipment',slot:'bag',bonus:{rapport:1}},matchbox:{name:'茶行火柴盒',desc:'盒底寫著一個印刷行地址。',type:'tool'},notebook:{name:'袖珍筆記本',desc:'可整理零碎線索。',type:'equipment',slot:'pocket',bonus:{insight:1}},meal_ticket:{name:'工廠餐券',desc:'一張尚未使用的餐券，也許能換來一頓飯或一份人情。',type:'consumable'},archive_pages:{name:'三頁失落筆記',desc:'阿川遺失的訪談與觀察紀錄。',type:'quest'},old_dictionary:{name:'缺頁字典',desc:'一本舊字典，夾層適合保存紙張。',type:'equipment',slot:'pocket',bonus:{knowledge:1}}};
const identityText={
intro:{student:'你剛把課堂借來的書放下，信封上的筆跡便讓你想到校內那些不願公開流傳的手抄文字。',worker:'你才從一天的工作回來，手上還留著洗不乾淨的油污。有人特地把信送到住處，這件事本身就讓你在意。',clerk:'你每天都接觸格式整齊的文件，因此第一眼就注意到：這封信刻意沒有日期、地址與寄件人。',reporter:'職業習慣讓你先看紙張、筆跡和措辭；它不像新聞線索，更像一個不希望留下來源的人在求助。',teacher:'你批改過太多學生的文字，知道一句話有時比寫信的人想像得更容易暴露情緒。阿川顯然很急。',merchant:'你習慣先判斷一件事值不值得投入時間。這封信沒有談錢，也沒有說明代價，反而更難估量。',veteran:'你曾經學會在資訊不足時不要急著下判斷。短短一句「別向別人提起」，讓你先把信收進內袋。',homemaker:'街坊每天都有消息流動，但真正重要的事往往說得最小聲。這封信讓你想到最近幾次欲言又止的鄰里談話。'},
print_shop:{student:'牆邊幾疊校刊尺寸的紙張先吸引了你的目光。你認得其中一些排版習慣。',worker:'你先注意到搬紙留下的磨痕與角落堆放方式；這裡的人每天搬動的東西比嘴上說的多。',clerk:'帳簿的欄位與收據擺法讓你很熟悉。周老闆雖然說得含糊，店裡的紀錄卻未必如此。',reporter:'你本能地掃過日期、紙張來源與桌上的名字。周老闆也很快看出你不是普通來客，語氣因此更保守。',teacher:'幾張試印紙上有常見教材用字。你知道這種小印刷行與學校、社團之間常有往來。',merchant:'你看得出周老闆正忙著趕幾筆生意；在生意人最忙的時候問私人問題，通常不是好時機。',veteran:'你沒有把周老闆短暫的停頓當成證據。經驗告訴你，緊張和隱瞞不是同一回事。',homemaker:'你注意到後間有人剛送過茶，櫃檯旁還放著鄰近店家的碗盤。這間店與附近街坊的關係比表面更密。'},
market:{student:'你對市場並不陌生，但攤販之間交換消息的速度仍比校園快得多。',worker:'幾個搬貨的人和你說話時少了些客套；工作留下的姿態與手掌，有時比介紹自己更快。',clerk:'你聽見攤商抱怨送貨、票據與公家規定。平日工作裡熟悉的制度，在這裡變成了每個人的生活成本。',reporter:'每個攤位似乎都有一個版本的故事。你的工作讓你知道，消息多不代表真相比較近。',teacher:'有幾個替家裡跑腿的孩子認出你的說話方式像老師，回答問題時不自覺站得更直。',merchant:'你不用刻意打聽就能聽懂攤商正在談的進貨與價格。誰和誰熟、貨從哪裡來，常藏在幾句討價還價裡。',veteran:'戰事新聞讓市場裡的議論比平常更緊繃。你聽得出哪些是親身消息，哪些只是把傳聞再說一次。',homemaker:'你熟悉這種地方的節奏。與其直接盤問，不如先聽賣菜、買米與排隊的人怎麼談昨天發生的事。'},
factory_branch:{student:'機器聲比你想像得更難讓人集中精神。筆記裡簡短的「夜班」兩字，在現場突然有了重量。',worker:'你幾乎不需要解釋自己為何理解輪班與工傷。工友看你的眼神和看一般訪客不同。',clerk:'你注意到出勤、請假與名冊都有固定格式，但紙面紀錄未必能說明一個人為何沒有來上班。',reporter:'你很清楚訪談可以留下故事，也可以讓受訪者感到被暴露。秋月曾經接受訪談這件事，讓你的記者身分變得敏感。',teacher:'「弟妹的學費」讓你停了一下。你見過學生因家庭收入改變而突然缺課，知道工廠與教室並不是兩個互不相干的世界。',merchant:'你從工廠外的貨車與交貨節奏看見另一種帳目：每次停工、缺勤與延誤最後都會變成成本。',veteran:'規律的機器聲讓你想起另一種集體生活，但你提醒自己不要拿自己的經歷替秋月解釋她的處境。',homemaker:'你最先在意的不是秋月缺勤，而是「父親病倒」後家裡還有誰能照顧、誰得出去工作。'}
};
const S=(chapter,location,date,title,text,choices)=>({chapter,location,date,title,text,choices}),C=(label,next,effects={},extra={})=>({label,next,effects,...extra});
const scenes={
intro:S('第一章・雨夜','臺北・大稻埕','1958 年 9 月','一封沒有署名的信',['傍晚的雨把街上的招牌洗得發亮。回到住處，你發現門縫下壓著一封沒有署名的信。','舊同學阿川邀你明晚到茶行見面，只寫著：「別向別人提起。」','你不知道這是一場普通求助，還是某件更大的事情的入口。'],[C('把信收好，明晚赴約','tea_shop',{stress:1}),C('先向共同朋友美惠打聽','ask_friend',{suspicion:1}),C('處理掉信，當作沒有看見','ignored',{composure:1})]),
ask_friend:S('第一章・雨夜','臺北・城中','1958 年 9 月','美惠的停頓',['美惠聽見阿川的名字時停頓了一瞬。她說阿川最近常往書店與印刷行跑。','「他不是在做壞事，只是太相信留下文字很重要。」她說。'],[C('停止追問，直接去見阿川','tea_shop',{rapport:1}),C('追問印刷行的位置','print_shop',{insight:1,suspicion:1})]),
ignored:S('第一章・雨夜','臺北・住處','1958 年 9 月','事情沒有因此消失',['兩天後，美惠主動來找你。阿川沒有回家，茶行老闆託她帶來一只火柴盒。','盒底寫著一個地址。'],[C('收下火柴盒，去印刷行','print_shop',{stress:1},{give:'matchbox'}),C('先找可信任的長輩商量','elder',{rapport:1},{give:'matchbox'})]),
tea_shop:S('第二章・暗語','臺北・茶行','1958 年 9 月','茶香裡的委託',['阿川正在整理工廠勞動、校園生活與普通人的訪談紀錄，但其中三頁不見了。','他真正害怕的，是內容脫離上下文後傷到被記錄的人。'],[C('答應幫忙找回失頁','investigate',{rep:1,stress:1}),C('先閱讀剩餘筆記','read_notes',{knowledge:1}),C('勸他停止，先保全自己','withdraw',{composure:1})]),
read_notes:S('第二章・暗語','臺北・茶行','1958 年 9 月','紙上的日常',['筆記不像宣言，而是工資、剪報、課堂見聞與訪談。','茶行老闆看你整理紙張，送你一本小筆記本。'],[C('協助找回失頁','investigate',{insight:1},{give:'notebook'}),C('找可信任的學者討論保存方式','professor',{knowledge:1,suspicion:1},{give:'notebook'})]),
withdraw:S('第二章・暗語','臺北・茶行後巷','1958 年 9 月','退後一步',['阿川沉默很久，最後把資料收回袋子。','你可以就此離開，也可以至少確認他平安回家。'],[C('陪阿川走一段路','investigate',{insight:1}),C('就此退出',null,{suspicion:-1},{ending:'quiet'})]),
elder:S('第二章・旁觀者','臺北・家中','1958 年 9 月','長輩的經驗',['長輩沒有鼓勵你冒險，也沒有要你立刻把東西交出去。','「先弄清楚手上的東西是什麼。」'],[C('依建議去印刷行查證','print_shop',{knowledge:1,composure:1}),C('把界線停在這裡',null,{stress:-1},{ending:'quiet'})]),
investigate:S('第三章・失頁','臺北・街區','1958 年 9 月','三條普通的路',['阿川最後整理資料的地方只有茶行、印刷行與市場。','你能依靠的只是觀察、記憶與別人願不願意相信你。'],[C('先去印刷行','print_shop'),C('先去市場','market',{rapport:1})]),
print_shop:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','油墨與廢紙',['周老闆的桌上堆著喜帖、傳單與帳簿。你提到阿川，他先否認，才反問：「你是找人，還是找紙？」','角落的廢紙簍裡，有半張與阿川筆記相似的紙。'],[C('坦白只想確認阿川與失頁','printer_truth',{rapport:1}),C('不急著說話，先觀察店裡','printer_observe',{insight:1},{requires:{insight:2}}),C('以採訪經驗分辨他避開的是哪個問題','printer_observe',{insight:1,suspicion:1},{onlyBg:'reporter'}),C('從帳簿與收據格式找出阿川留下的紀錄','printer_observe',{knowledge:1},{onlyBg:'clerk'})]),
printer_observe:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','被撕掉的一角',['你看見借物清單上寫著「川：鉛字盒一只」。周老闆確實認識阿川。','你沒有立刻揭穿他。'],[C('用線索換取實話','printer_truth',{rep:1})]),
printer_truth:S('第三章・失頁','臺北・印刷行後間','1958 年 9 月','廢紙去了市場',['周老闆承認阿川來過。三頁紙可能混進廢紙，被替市場跑腿的少年帶走。','他提醒你別一開口就盤問那孩子。'],[C('前往市場','market',{rapport:1},{give:'meal_ticket'})]),
market:S('第四章・市場','臺北・市場','1958 年 9 月','一張包過花生的紙',['跑腿少年承認拿過一疊廢紙，其中幾張包過花生，其餘送到舊書攤。','他說昨天也有人問過「印著奇怪文字的紙」。'],[C('直接去舊書攤','bookstall',{stress:1}),C('耐心問清楚昨天那個人','uniform',{insight:1},{requires:{rapport:2}}),C('把餐券送給少年，再請他回想','uniform',{rapport:1},{requiresItem:'meal_ticket',consume:'meal_ticket'}),C('先和熟悉的攤販聊幾句再問','uniform',{rapport:1},{onlyBg:'merchant'}),C('從街坊閒談中拼出那人的去向','uniform',{insight:1},{onlyBg:'homemaker'})]),
uniform:S('第四章・市場','臺北・市場','1958 年 9 月','也許只是例行',['少年記得那名詢問者穿郵務制服，也在找一封寄錯地址的信。','這不能證明完全沒有風險，但模糊資訊也不該被當成確定威脅。'],[C('前往舊書攤','bookstall',{composure:1,suspicion:-1})]),
bookstall:S('第五章・失而復得','臺北・舊書攤','1958 年 9 月','三頁紙',['老闆從一本缺頁字典裡抽出三張折好的紙。','失頁找回來了。真正的問題變成「該怎麼處理」。'],[C('把三頁完整交還阿川','archive',{rep:1},{give:'archive_pages'}),C('提出匿名化後再保存','redact',{knowledge:1},{requires:{knowledge:3},give:'archive_pages'}),C('請可信任的學者協助判斷','professor',{suspicion:1},{give:'archive_pages'})]),
professor:S('第六章・保存','臺北・教授宿舍','1958 年 10 月','保存也是責任',['教授指出最危險的是能辨認受訪者的細節。','他建議把姓名、單位與可追溯資訊分離。'],[C('採用匿名封存方案',null,{rep:2,suspicion:-1},{ending:'careful'}),C('暫時不保留可辨認資料',null,{composure:2},{ending:'people'})]),
archive:S('第六章・封存','臺北・茶行','1958 年 10 月','完整，卻不公開',['阿川同意不再複製資料，先將內容封存。','這些紀錄背後還有更多人的故事。'],[C('繼續追查筆記中的工廠訪談','factory_branch',{rep:1}),C('在這裡停下',null,{composure:1},{ending:'sealed'})]),
redact:S('第六章・去名','臺北・印刷行','1958 年 10 月','留下事情，不留下名字',['你們把姓名、地址、單位與可追溯線索分開。','阿川第一次承認：「真實」不一定等於「全部留下」。'],[C('繼續調查工廠訪談','factory_branch',{rep:2}),C('完成後收手',null,{rep:1},{ending:'careful'})]),
factory_branch:S('第七章・機器聲','臺北・近郊紡織廠','1958 年 10 月','筆記裡的名字',['失頁中的訪談提到女工「秋月」。她談的是夜班、工傷與家中弟妹的學費。','你來到工廠附近，卻發現她已數日沒有上班。'],[C('先和工友建立信任','factory_friend',{rapport:1}),C('直接去秋月留下的地址','qiuyue_home',{stress:1}),C('以工作經驗和工友聊起輪班','factory_friend',{composure:1,rapport:1},{onlyBg:'worker'}),C('以教師身分詢問弟妹是否需要協助','factory_friend',{rapport:1},{onlyBg:'teacher'})]),
factory_friend:S('第七章・機器聲','臺北・工廠外','1958 年 10 月','沒有人只活在一條線裡',['工友說秋月的父親病倒，她暫時回家照顧。她曾擔心訪談說得太多，希望阿川不要留下真名。'],[C('去秋月家，先徵詢她本人','qiuyue_home',{rep:1}),C('不打擾她，回去刪除可辨識資料',null,{composure:2},{ending:'consent'})]),
qiuyue_home:S('第八章・門內','臺北・萬華','1958 年 10 月','秋月的選擇',['秋月對你的到來很戒備。當你說明阿川的筆記，她沉默許久。','她說：「我的名字不要留。但如果以後有人想知道我們怎麼過日子，其他的可以留下。」'],[C('尊重她的條件，重新整理','night_archive',{rep:2,knowledge:1}),C('整段訪談都不保留',null,{composure:2},{ending:'people'})]),
night_archive:S('第九章・夜間檔案','臺北・印刷行','1958 年 11 月','新的方法',['你們建立規則：受訪者決定是否留名；敏感身分資料與內容分開；紀錄標明來源可信程度。','這件事逐漸成為一項更漫長的工作。'],[C('長期協助整理口述紀錄',null,{rep:3},{ending:'archivist'}),C('把方法留下，回到自己的生活',null,{composure:2},{ending:'return'})])};
const endings={quiet:{title:'結局：保持距離',text:'你選擇不再介入，為自己劃出界線。'},careful:{title:'結局：無名的檔案',text:'事件被留下，名字則被謹慎移除。'},people:{title:'結局：人比紙重要',text:'你選擇優先降低當事人的風險。'},sealed:{title:'結局：封存的記憶',text:'第一批資料被完整但低調地封存。'},consent:{title:'結局：未被打擾的人',text:'你依秋月曾表達的顧慮移除可辨識資訊。'},archivist:{title:'結局：霧中的記錄者',text:'你持續確認、整理、去名、詢問同意，普通人的生活因此留下痕跡。'},return:{title:'結局：把方法留下',text:'你離開整理工作，但你們建立的方法被保留下來。'}};
const $=id=>document.getElementById(id),el={startScreen:$('startScreen'),gameScreen:$('gameScreen'),endingScreen:$('endingScreen'),nameInput:$('nameInput'),backgroundChoices:$('backgroundChoices'),startBtn:$('startBtn'),loadStartBtn:$('loadStartBtn'),playerName:$('playerName'),playerBg:$('playerBg'),passiveName:$('passiveName'),stress:$('stress'),rep:$('rep'),suspicion:$('suspicion'),attributeBar:$('attributeBar'),chapter:$('chapter'),location:$('location'),sceneDate:$('sceneDate'),sceneTitle:$('sceneTitle'),sceneText:$('sceneText'),choices:$('choices'),saveBtn:$('saveBtn'),inventoryBtn:$('inventoryBtn'),logBtn:$('logBtn'),restartBtn:$('restartBtn'),inventoryPanel:$('inventoryPanel'),inventoryList:$('inventoryList'),equipmentList:$('equipmentList'),closeInventoryBtn:$('closeInventoryBtn'),logPanel:$('logPanel'),logList:$('logList'),closeLogBtn:$('closeLogBtn'),endingTitle:$('endingTitle'),endingText:$('endingText'),endingStats:$('endingStats'),againBtn:$('againBtn'),menuBtn:$('menuBtn'),menu:$('menu'),menuClose:$('menuClose'),menuSave:$('menuSave'),menuLoad:$('menuLoad'),menuRestart:$('menuRestart'),backdrop:$('backdrop'),toast:$('toast')};let selectedBg=null,state=null,timer=null;
function newState(name,bg){let b=backgrounds[bg];return{version:3,name:name.trim()||'無名旅人',bg,scene:'intro',stress:0,rep:0,suspicion:0,attributes:{...b.stats},inventory:[...b.items],equipment:{},visited:[],log:[{title:'故事開始',text:`1958 年 9 月，你以${b.label}的身分收到一封沒有署名的信。`}],finished:false}}
const clamp=(n,min=0,max=99)=>Math.max(min,Math.min(max,n));function eff(e={}){let changes=[];for(let k of ['stress','rep','suspicion'])if(typeof e[k]==='number'){state[k]=clamp(state[k]+e[k]);changes.push(`${{stress:'壓力',rep:'聲望',suspicion:'疑心'}[k]} ${e[k]>0?'+':''}${e[k]}`)}for(let k of ['insight','knowledge','composure','rapport'])if(typeof e[k]==='number'){state.attributes[k]=clamp(state.attributes[k]+e[k],0,20);changes.push(`${{insight:'觀察',knowledge:'知識',composure:'沉著',rapport:'人情'}[k]} ${e[k]>0?'+':''}${e[k]}`)}return changes}
function req(c){if(c.onlyBg&&c.onlyBg!==state.bg)return false;if(c.requiresItem&&!state.inventory.includes(c.requiresItem))return false;return Object.entries(c.requires||{}).every(([k,v])=>(k in state.attributes?state.attributes[k]:state[k])>=v)}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function showToast(m){clearTimeout(timer);el.toast.textContent=m;el.toast.classList.add('show');timer=setTimeout(()=>el.toast.classList.remove('show'),2200)}
function renderStatus(){let b=backgrounds[state.bg]||backgrounds.student;el.playerName.textContent=state.name;el.playerBg.textContent=b.label;el.passiveName.textContent=b.passive;el.stress.textContent=state.stress;el.rep.textContent=state.rep;el.suspicion.textContent=state.suspicion;el.attributeBar.innerHTML=`<span>觀察 <b>${state.attributes.insight}</b></span><span>知識 <b>${state.attributes.knowledge}</b></span><span>沉著 <b>${state.attributes.composure}</b></span><span>人情 <b>${state.attributes.rapport}</b></span>`}
function renderScene(){let s=scenes[state.scene];if(!s)return showToast('找不到場景');showScreen('game');renderStatus();el.chapter.textContent=s.chapter;el.location.textContent=s.location;el.sceneDate.textContent=s.date;el.sceneTitle.textContent=s.title;let paras=s.text.map(p=>`<p>${esc(p)}</p>`);let variant=identityText[state.scene]?.[state.bg];if(variant)paras.splice(1,0,`<p class="identity-text"><b>${esc(backgrounds[state.bg].passive)}</b>｜${esc(variant)}</p>`);el.sceneText.innerHTML=paras.join('');el.choices.innerHTML='';s.choices.filter(c=>!c.onlyBg||c.onlyBg===state.bg).forEach(c=>{let ok=req(c),b=document.createElement('button');b.className='choice-btn'+(ok?'':' locked');b.disabled=!ok;let locked=!ok?(c.requiresItem?`需要道具：${items[c.requiresItem].name}`:'條件不足'):'';b.innerHTML=`<strong>${esc(c.label)}</strong>${locked?`<small>${esc(locked)}</small>`:''}`;b.onclick=()=>choose(c);el.choices.appendChild(b)});window.scrollTo({top:0,behavior:'smooth'})}
function give(id){if(id&&!state.inventory.includes(id))state.inventory.push(id)}function choose(c){if(!req(c))return;let changes=eff(c.effects),notes=[];if(c.give&&!state.inventory.includes(c.give)){give(c.give);notes.push(`獲得 ${items[c.give].name}`)}if(c.consume){state.inventory=state.inventory.filter(x=>x!==c.consume);notes.push(`使用 ${items[c.consume].name}`)}if(changes.length)notes.push(changes.join('・'));if(notes.length)showToast(notes.join('｜'));state.log.unshift({title:scenes[state.scene].title,text:`你選擇了「${c.label}」。`});if(c.ending)return finish(c.ending);state.scene=c.next;autoSave();renderScene()}
function equip(id){let it=items[id];if(!it||it.type!=='equipment')return;let old=state.equipment[it.slot];if(old===id){delete state.equipment[it.slot];eff(Object.fromEntries(Object.entries(it.bonus||{}).map(([k,v])=>[k,-v])));showToast(`卸下：${it.name}`)}else{if(old){let oi=items[old];eff(Object.fromEntries(Object.entries(oi.bonus||{}).map(([k,v])=>[k,-v])))}state.equipment[it.slot]=id;eff(it.bonus);showToast(`裝備：${it.name}`)}renderStatus();renderInventory();autoSave()}
function renderInventory(){let eq=Object.values(state.equipment);el.equipmentList.innerHTML=`<div class="equipment-box"><strong>被動｜${esc(backgrounds[state.bg].passive)}</strong><br><small>${eq.length?'裝備：'+eq.map(x=>items[x]?.name||x).join('・'):'尚未裝備任何物品'}</small></div>`;el.inventoryList.innerHTML=state.inventory.map(id=>{let i=items[id];if(!i)return'';let equipped=Object.values(state.equipment).includes(id);return `<div class="item-card"><strong>${esc(i.name)}</strong><small>${esc(i.desc)}</small>${i.type==='equipment'?`<button class="item-btn" data-equip="${id}">${equipped?'卸下':'裝備'}</button>`:''}</div>`}).join('')||'<div class="item-card">行囊是空的。</div>';el.inventoryList.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.equip))}
function finish(id){let e=endings[id];state.finished=true;state.ending=id;autoSave();showScreen('ending');el.endingTitle.textContent=e.title;el.endingText.textContent=e.text;el.endingStats.innerHTML=`<span>壓力<b>${state.stress}</b></span><span>聲望<b>${state.rep}</b></span><span>疑心<b>${state.suspicion}</b></span>`;window.scrollTo({top:0,behavior:'smooth'})}function renderLog(){el.logList.innerHTML=state.log.map(x=>`<div class="log-entry"><b>${esc(x.title)}</b><br>${esc(x.text)}</div>`).join('')}function autoSave(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(_){}}function save(){if(!state)return showToast('沒有可保存的進度');autoSave();showToast('進度已保存在此裝置')}
function migrate(s){if(!s)return null;if(!backgrounds[s.bg])s.bg='student';s.version=3;s.inventory=(s.inventory||[]).filter(id=>items[id]);s.equipment=s.equipment||{};s.attributes=s.attributes||{...backgrounds[s.bg].stats};return s}function load(){try{state=JSON.parse(localStorage.getItem(SAVE_KEY)||localStorage.getItem(OLD_SAVE_KEY));state=migrate(state)}catch(_){state=null}if(!state)return showToast('找不到存檔');autoSave();closeMenu();state.finished?finish(state.ending):renderScene();showToast('已讀取存檔')}
function restart(){if(!confirm('要放棄目前進度並回到開始畫面嗎？'))return;state=null;selectedBg=null;el.nameInput.value='';[...el.backgroundChoices.querySelectorAll('.bg-choice')].forEach(b=>b.classList.remove('selected'));el.startBtn.disabled=true;closeMenu();showScreen('start')}function showScreen(w){el.startScreen.classList.toggle('hidden',w!=='start');el.gameScreen.classList.toggle('hidden',w!=='game');el.endingScreen.classList.toggle('hidden',w!=='ending')}function openMenu(){el.menu.classList.remove('hidden');el.backdrop.classList.remove('hidden')}function closeMenu(){el.menu.classList.add('hidden');el.backdrop.classList.add('hidden')}
el.backgroundChoices.onclick=e=>{let b=e.target.closest('.bg-choice');if(!b)return;selectedBg=b.dataset.bg;[...el.backgroundChoices.querySelectorAll('.bg-choice')].forEach(x=>x.classList.toggle('selected',x===b));el.startBtn.disabled=false};el.startBtn.onclick=()=>{state=newState(el.nameInput.value,selectedBg);autoSave();renderScene()};el.loadStartBtn.onclick=load;el.saveBtn.onclick=save;el.inventoryBtn.onclick=()=>{renderInventory();el.inventoryPanel.classList.toggle('hidden');el.logPanel.classList.add('hidden')};el.closeInventoryBtn.onclick=()=>el.inventoryPanel.classList.add('hidden');el.logBtn.onclick=()=>{renderLog();el.logPanel.classList.toggle('hidden');el.inventoryPanel.classList.add('hidden')};el.closeLogBtn.onclick=()=>el.logPanel.classList.add('hidden');el.restartBtn.onclick=restart;el.againBtn.onclick=restart;el.menuBtn.onclick=openMenu;el.menuClose.onclick=closeMenu;el.backdrop.onclick=closeMenu;el.menuSave.onclick=save;el.menuLoad.onclick=load;el.menuRestart.onclick=restart;})();