(()=>{'use strict';
const SAVE_KEY='mist-taiwan-rpg-save-v2';
const backgrounds={student:{label:'學生',stats:{insight:2,knowledge:2,composure:0,rapport:0},item:'student_id'},worker:{label:'工人',stats:{insight:0,knowledge:0,composure:2,rapport:2},item:'work_gloves'},clerk:{label:'職員',stats:{insight:1,knowledge:0,composure:0,rapport:3},item:'fountain_pen'}};
const items={student_id:{name:'學生證',desc:'證明學生身分；在校園與書店場合可能派上用場。',type:'tool'},work_gloves:{name:'舊工作手套',desc:'粗厚耐用，帶著工廠生活留下的痕跡。',type:'equipment',slot:'hand',bonus:{composure:1}},fountain_pen:{name:'鋼筆',desc:'一支體面的鋼筆，適合記錄與公務場合。',type:'equipment',slot:'hand',bonus:{rapport:1}},matchbox:{name:'茶行火柴盒',desc:'盒底寫著一個印刷行地址。',type:'tool'},notebook:{name:'袖珍筆記本',desc:'可整理零碎線索。',type:'equipment',slot:'pocket',bonus:{insight:1}},meal_ticket:{name:'工廠餐券',desc:'一張尚未使用的餐券，也許能換來一頓飯或一份人情。',type:'consumable'},archive_pages:{name:'三頁失落筆記',desc:'阿川遺失的訪談與觀察紀錄。',type:'quest'},old_dictionary:{name:'缺頁字典',desc:'舊書攤老闆送你的舊字典，夾層適合藏紙。',type:'equipment',slot:'pocket',bonus:{knowledge:1}}};
const S=(chapter,location,date,title,text,choices,onEnter)=>({chapter,location,date,title,text,choices,onEnter});
const C=(label,next,effects={},extra={})=>({label,next,effects,...extra});
const scenes={
intro:S('第一章・雨夜','臺北・大稻埕','1958 年 9 月','一封沒有署名的信',['傍晚的雨把街上的招牌洗得發亮。回到住處，你發現門縫下壓著一封沒有署名的信。','舊同學阿川邀你明晚到茶行見面，只寫著：「別向別人提起。」','你不知道這是一場普通求助，還是某件更大的事情的入口。'],[C('把信收好，明晚赴約','tea_shop',{stress:1},{log:'你決定赴約。'}),C('先向共同朋友美惠打聽','ask_friend',{suspicion:1},{log:'你先打聽阿川的近況。'}),C('處理掉信，當作沒有看見','ignored',{composure:1},{log:'你選擇暫時保持距離。'})]),
ask_friend:S('第一章・雨夜','臺北・城中','1958 年 9 月','美惠的停頓',['美惠聽見阿川的名字時停頓了一瞬。她說阿川最近常往書店與印刷行跑。','「他不是在做壞事，只是太相信留下文字很重要。」她說。你沒有追問她為什麼知道。'],[C('停止追問，直接去見阿川','tea_shop',{rapport:1}),C('追問印刷行的位置','print_shop',{insight:1,suspicion:1})]),
ignored:S('第一章・雨夜','臺北・住處','1958 年 9 月','事情沒有因此消失',['兩天後，美惠主動來找你。阿川沒有回家，茶行老闆託她帶來一只火柴盒。','盒底寫著一個地址。你本來想離事情遠一點，但現在有人正在等你的決定。'],[C('收下火柴盒，去印刷行','print_shop',{stress:1},{give:'matchbox'}),C('先找可信任的長輩商量','elder',{rapport:1},{give:'matchbox'})]),
tea_shop:S('第二章・暗語','臺北・茶行','1958 年 9 月','茶香裡的委託',['阿川比記憶中疲憊。他正在整理工廠勞動、校園生活與普通人的訪談紀錄，但其中三頁不見了。','那些紙上沒有行動計畫。他真正害怕的，是內容脫離上下文後傷到被記錄的人。'],[C('答應幫忙找回失頁','investigate',{rep:1,stress:1}),C('先閱讀剩餘筆記','read_notes',{knowledge:1}),C('勸他停止，先保全自己','withdraw',{composure:1})]),
read_notes:S('第二章・暗語','臺北・茶行','1958 年 9 月','紙上的日常',['筆記不像宣言，而是工資、剪報、課堂見聞與訪談。你開始理解：記錄本身沒有單一意義。','茶行老闆看你反覆整理紙張，送你一本小筆記本：「至少別把線索都記在腦子裡。」'],[C('協助找回失頁','investigate',{insight:1},{give:'notebook'}),C('找一位可信任的學者討論保存方式','professor',{knowledge:1,suspicion:1},{give:'notebook'})]),
withdraw:S('第二章・暗語','臺北・茶行後巷','1958 年 9 月','退後一步',['阿川沉默很久，最後把資料收回袋子。你們走出茶行，街上只是普通的雨夜。','你可以就此離開，也可以至少確認他平安回家。'],[C('陪阿川走一段路','tail',{insight:1,stress:1}),C('就此退出',null,{suspicion:-1},{ending:'quiet'})]),
tail:S('第二章・暗語','臺北・街道','1958 年 9 月','身後的腳步',['一名男子與你們同路兩條街。你們停在麵攤，他繼續往前，沒有回頭。','也許只是同路。阿川終於承認，恐懼有時會讓人把所有巧合都看成訊號。'],[C('仍幫他把失頁找回來','investigate',{composure:1})]),
elder:S('第二章・旁觀者','臺北・家中','1958 年 9 月','長輩的經驗',['長輩沒有鼓勵你冒險，也沒有要你立刻把東西交出去。','「先弄清楚手上的東西是什麼。不要因害怕替別人定罪，也別因相信朋友忽略風險。」'],[C('依建議去印刷行查證','print_shop',{knowledge:1,composure:1}),C('把界線停在這裡',null,{stress:-1},{ending:'quiet'})]),
investigate:S('第三章・失頁','臺北・街區','1958 年 9 月','三條普通的路',['阿川最後整理資料的地方只有茶行、印刷行與市場。你們決定分開查找。','這不是偵探故事。你能依靠的只是觀察、記憶與別人願不願意相信你。'],[C('先去印刷行','print_shop'),C('先去市場','market',{rapport:1})]),
print_shop:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','油墨與廢紙',['周老闆的桌上堆著喜帖、傳單與帳簿。你提到阿川，他先否認，才反問：「你是找人，還是找紙？」','角落的廢紙簍裡，有半張與阿川筆記相似的紙。'],[C('坦白只想確認阿川與失頁','printer_truth',{rapport:1}),C('假裝來問印刷社團刊物','printer_bluff',{suspicion:1}),C('不急著說話，先觀察店裡','printer_observe',{insight:1},{requires:{insight:2},lockedHint:'需要觀察 ≥ 2'})]),
printer_bluff:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','一句太完整的謊話',['你的說法準備得太完整，反而讓周老闆起疑。他沒有拆穿，只把價目表推來。','離開前他說：「真正保護人的，有時不是聰明，是知道什麼時候別多說。」'],[C('改口坦白','printer_truth',{stress:1}),C('離開去找美惠','meihui',{suspicion:-1})]),
printer_observe:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','被撕掉的一角',['你看見借物清單上寫著「川：鉛字盒一只」。周老闆確實認識阿川。','你沒有立刻揭穿他，而是把這件事記在心裡。'],[C('用線索換取實話','printer_truth',{rep:1}),C('不逼問，轉去找美惠','meihui',{suspicion:-1})]),
printer_truth:S('第三章・失頁','臺北・印刷行後間','1958 年 9 月','廢紙去了市場',['周老闆承認阿川來過。三頁紙可能混進一疊廢紙，被一名替市場跑腿的少年帶走。','他還塞給你一張工廠餐券：「那孩子常餓著肚子跑腿，別一開口就盤問人家。」'],[C('前往市場','market',{rapport:1},{give:'meal_ticket'}),C('先把消息告訴阿川','tell_achuan',{composure:1},{give:'meal_ticket'})]),
meihui:S('第三章・失頁','臺北・公車站','1958 年 9 月','美惠知道的另一半',['美惠記得阿川曾幫印刷行搬廢紙。她提醒你別把每個模糊線索都想成陰謀。','「有時候一張紙真的只是被風吹走。」'],[C('去市場找廢紙去向','market',{composure:1})]),
tell_achuan:S('第三章・失頁','臺北・河岸','1958 年 9 月','阿川的急躁',['阿川聽完立刻想逐攤詢問。你看得出焦慮正在讓他失去判斷。','你提醒他，慌張本身也會留下痕跡。'],[C('讓阿川留下，由你單獨去','market',{composure:1}),C('一起去市場','market',{rep:1,suspicion:1})]),
market:S('第四章・市場','臺北・市場','1958 年 9 月','一張包過花生的紙',['市場只在意魚價、雨勢與今天能不能把貨賣完。跑腿少年承認拿過一疊廢紙，其中幾張包過花生，其餘送到舊書攤。','他說昨天也有人問過「印著奇怪文字的紙」。你不知道那代表什麼。'],[C('直接去舊書攤','bookstall',{stress:1}),C('耐心問清楚昨天那個人','uniform',{insight:1},{requires:{rapport:2},lockedHint:'需要人情 ≥ 2'}),C('把餐券送給少年，再請他回想','market_help',{rapport:1},{requiresItem:'meal_ticket',consume:'meal_ticket'})]),
market_help:S('第四章・市場','臺北・市場','1958 年 9 月','一頓飯換來的記憶',['少年收下餐券後不是突然變得健談，只是願意多想一會兒。','他記起那名詢問者穿的是郵務制服，而且一路在找一封寄錯地址的信。這不能證明完全沒有風險，但至少讓一個可怕的猜測少了幾分根據。'],[C('安心一些，去舊書攤','bookstall',{composure:2,suspicion:-1})]),
uniform:S('第四章・市場','臺北・市場','1958 年 9 月','也許只是例行',['少年只記得對方態度平常。你無法證實他的身分，也沒有理由把模糊資訊當成確定威脅。','你決定把注意力放回能確認的事情：那三頁紙。'],[C('前往舊書攤','bookstall',{composure:1,suspicion:-1})]),
bookstall:S('第五章・失而復得','臺北・舊書攤','1958 年 9 月','三頁紙',['老闆從一本缺頁字典裡抽出三張折好的紙。他覺得不像普通廢紙，便先收了起來。','失頁找回來了。真正的問題從「在哪裡」變成「該怎麼處理」。'],[C('把三頁完整交還阿川','archive',{rep:1},{give:'archive_pages'}),C('提出匿名化後再保存','redact',{knowledge:1},{requires:{knowledge:3},lockedHint:'需要知識 ≥ 3',give:'archive_pages'}),C('請可信任的學者協助判斷','professor',{suspicion:1},{give:'archive_pages'}),C('買下那本缺頁字典作為保管工具','archive',{knowledge:1},{give:'old_dictionary'})]),
professor:S('第六章・保存','臺北・教授宿舍','1958 年 10 月','保存也是責任',['教授沒有評論立場，只指出最危險的是能辨認受訪者的細節。','他建議把姓名、單位與可追溯資訊分離。保存不是把一切原封不動留下，而是對未來與當事人同時負責。'],[C('採用匿名封存方案',null,{rep:2,suspicion:-1},{ending:'careful'}),C('暫時不保留可辨認資料',null,{composure:2},{ending:'people'})]),
archive:S('第六章・封存','臺北・茶行','1958 年 10 月','完整，卻不公開',['阿川同意不再複製資料，先將內容封存。美惠負責整理日期，周老闆提供乾燥的木箱。','事情沒有因此結束。你開始意識到，這些紀錄背後還有更多人的故事。'],[C('完成第一批封存，繼續追查筆記中的工廠訪談','factory_branch',{rep:1}),C('在這裡停下',null,{composure:1},{ending:'sealed'})]),
redact:S('第六章・去名','臺北・印刷行','1958 年 10 月','留下事情，不留下名字',['你們把姓名、地址、單位與可追溯線索分開，只留下事件、日期與感受。','阿川第一次承認：「真實」不一定等於「全部留下」。'],[C('完成匿名紀錄並繼續調查工廠訪談','factory_branch',{rep:2,composure:1}),C('完成後就此收手',null,{rep:1},{ending:'careful'})]),
factory_branch:S('第七章・機器聲','臺北・近郊紡織廠','1958 年 10 月','筆記裡的名字',['失頁中的一段訪談提到一名女工「秋月」。她抱怨的不是政治，而是夜班、工傷與家中弟妹的學費。','你循著線索來到工廠附近，卻發現她已數日沒有上班。工友只說：「家裡出了事。」'],[C('先和工友建立信任','factory_friend',{rapport:1}),C('直接去秋月留下的地址','qiuyue_home',{stress:1}),C('以工作背景和工友聊天','factory_friend',{composure:1,rapport:1},{requiresBg:'worker',hint:'你的工人背景讓這段對話自然許多'})]),
factory_friend:S('第七章・機器聲','臺北・工廠外','1958 年 10 月','沒有人只活在一條線裡',['工友告訴你，秋月的父親病倒，她暫時回家照顧。她曾擔心自己在訪談裡說得太多，希望阿川不要留下真名。','這讓「保存紀錄」第一次變成一個具體的人，而不是抽象原則。'],[C('去秋月家，先徵詢她本人','qiuyue_home',{rep:1}),C('不打擾她，回去刪除可辨識資料',null,{composure:2},{ending:'consent'})]),
qiuyue_home:S('第八章・門內','臺北・萬華','1958 年 10 月','秋月的選擇',['秋月對你的到來很戒備。當你說明阿川的筆記，她沉默許久。','她沒有要求全部銷毀，只說：「我的名字不要留。但如果以後有人想知道我們怎麼過日子，其他的可以留下。」'],[C('尊重她的條件，回去重新整理','night_archive',{rep:2,knowledge:1}),C('認為風險太高，整段訪談都不保留',null,{composure:2},{ending:'people'})]),
night_archive:S('第九章・夜間檔案','臺北・印刷行','1958 年 11 月','新的方法',['你們建立了一套規則：受訪者可以決定是否留名；敏感身分資料與內容分開；每份紀錄標明來源可信程度。','阿川原本只想「把東西留下」，現在這件事逐漸成為一項更漫長的工作。窗外，冬天快到了。'],[C('接受長期協助整理口述紀錄',null,{rep:3},{ending:'archivist'}),C('把方法交給阿川，回到自己的生活',null,{composure:2},{ending:'return'})])};
const endings={quiet:{title:'結局：保持距離',text:'你選擇不再介入。這不是勇敢或懦弱的簡單分類，而是你為自己劃出的界線。'},careful:{title:'結局：無名的檔案',text:'事件被留下，名字則被謹慎移除。多年後，它也許會成為理解那個年代的一小塊拼圖。'},people:{title:'結局：人比紙重要',text:'你選擇優先降低當事人的風險。有些細節因此消失，而你接受歷史保存從來沒有完美答案。'},sealed:{title:'結局：封存的記憶',text:'第一批資料被完整但低調地封存。你不知道它何時重新被打開，但至少它沒有完全消失。'},consent:{title:'結局：未被打擾的人',text:'你沒有把秋月變成故事素材，而是依她曾表達的顧慮移除可辨識資訊。保存開始有了界線。'},archivist:{title:'結局：霧中的記錄者',text:'你沒有成為英雄。接下來的日子裡，你只是反覆確認、整理、去名、詢問同意。也正因如此，普通人的生活有了一點被留下的可能。'},return:{title:'結局：把方法留下',text:'你離開了整理工作，但你們建立的方法被保留下來。阿川終於明白，記錄不是占有別人的故事。'}};
const $=id=>document.getElementById(id),el={startScreen:$('startScreen'),gameScreen:$('gameScreen'),endingScreen:$('endingScreen'),nameInput:$('nameInput'),backgroundChoices:$('backgroundChoices'),startBtn:$('startBtn'),loadStartBtn:$('loadStartBtn'),playerName:$('playerName'),playerBg:$('playerBg'),stress:$('stress'),rep:$('rep'),suspicion:$('suspicion'),attributeBar:$('attributeBar'),chapter:$('chapter'),location:$('location'),sceneDate:$('sceneDate'),sceneTitle:$('sceneTitle'),sceneText:$('sceneText'),choices:$('choices'),saveBtn:$('saveBtn'),inventoryBtn:$('inventoryBtn'),logBtn:$('logBtn'),restartBtn:$('restartBtn'),inventoryPanel:$('inventoryPanel'),inventoryList:$('inventoryList'),equipmentList:$('equipmentList'),closeInventoryBtn:$('closeInventoryBtn'),logPanel:$('logPanel'),logList:$('logList'),closeLogBtn:$('closeLogBtn'),endingTitle:$('endingTitle'),endingText:$('endingText'),endingStats:$('endingStats'),againBtn:$('againBtn'),menuBtn:$('menuBtn'),menu:$('menu'),menuClose:$('menuClose'),menuSave:$('menuSave'),menuLoad:$('menuLoad'),menuRestart:$('menuRestart'),backdrop:$('backdrop'),toast:$('toast')};let selectedBg=null,state=null,timer=null;
function newState(name,bg){let b=backgrounds[bg];return{version:2,name:name.trim()||'無名旅人',bg,scene:'intro',stress:0,rep:0,suspicion:0,attributes:{...b.stats},inventory:[b.item],equipment:{},visited:[],log:[{title:'故事開始',text:'1958 年 9 月，你收到一封沒有署名的信。'}],finished:false}}
const clamp=(n,min=0,max=99)=>Math.max(min,Math.min(max,n));function eff(e={}){let changes=[];for(let k of ['stress','rep','suspicion'])if(typeof e[k]==='number'){state[k]=clamp(state[k]+e[k]);changes.push(`${{stress:'壓力',rep:'聲望',suspicion:'疑心'}[k]} ${e[k]>0?'+':''}${e[k]}`)}for(let k of ['insight','knowledge','composure','rapport'])if(typeof e[k]==='number'){state.attributes[k]=clamp(state.attributes[k]+e[k],0,20);changes.push(`${{insight:'觀察',knowledge:'知識',composure:'沉著',rapport:'人情'}[k]} ${e[k]>0?'+':''}${e[k]}`)}return changes}
function req(c){if(c.requiresBg&&c.requiresBg!==state.bg)return false;if(c.requiresItem&&!state.inventory.includes(c.requiresItem))return false;return Object.entries(c.requires||{}).every(([k,v])=>(k in state.attributes?state.attributes[k]:state[k])>=v)}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function showToast(m){clearTimeout(timer);el.toast.textContent=m;el.toast.classList.add('show');timer=setTimeout(()=>el.toast.classList.remove('show'),2200)}
function renderStatus(){el.playerName.textContent=state.name;el.playerBg.textContent=backgrounds[state.bg].label;el.stress.textContent=state.stress;el.rep.textContent=state.rep;el.suspicion.textContent=state.suspicion;el.attributeBar.innerHTML=`<span>觀察 <b>${state.attributes.insight}</b></span><span>知識 <b>${state.attributes.knowledge}</b></span><span>沉著 <b>${state.attributes.composure}</b></span><span>人情 <b>${state.attributes.rapport}</b></span>`}
function renderScene(){let s=scenes[state.scene];if(!s)return showToast('找不到場景');showScreen('game');renderStatus();el.chapter.textContent=s.chapter;el.location.textContent=s.location;el.sceneDate.textContent=s.date;el.sceneTitle.textContent=s.title;el.sceneText.innerHTML=s.text.map(p=>`<p>${esc(p)}</p>`).join('');el.choices.innerHTML='';s.choices.forEach(c=>{let ok=req(c),b=document.createElement('button');b.className='choice-btn'+(ok?'':' locked');b.disabled=!ok;let locked=!ok?(c.lockedHint||(c.requiresItem?`需要道具：${items[c.requiresItem].name}`:c.requiresBg?`需要背景：${backgrounds[c.requiresBg].label}`:'條件不足')):'';b.innerHTML=`<strong>${esc(c.label)}</strong>${c.hint?`<small>${esc(c.hint)}</small>`:''}${locked?`<small>${esc(locked)}</small>`:''}`;b.onclick=()=>choose(c);el.choices.appendChild(b)});scrollTo({top:0,behavior:'smooth'})}
function give(id){if(id&&!state.inventory.includes(id)){state.inventory.push(id);showToast(`獲得道具：${items[id].name}`)}}function choose(c){if(!req(c))return;let changes=eff(c.effects);if(c.give)give(c.give);if(c.consume){state.inventory=state.inventory.filter(x=>x!==c.consume);showToast(`使用：${items[c.consume].name}`)}if(changes.length)setTimeout(()=>showToast('屬性變動｜'+changes.join('・')),150);state.log.unshift({title:scenes[state.scene].title,text:c.log||`你選擇了「${c.label}」。`});if(c.ending)return finish(c.ending);state.scene=c.next;autoSave();renderScene()}
function equip(id){let it=items[id];if(!it||it.type!=='equipment')return;let old=state.equipment[it.slot];if(old===id){delete state.equipment[it.slot];eff(Object.fromEntries(Object.entries(it.bonus||{}).map(([k,v])=>[k,-v])));showToast(`卸下：${it.name}`)}else{if(old){let oi=items[old];eff(Object.fromEntries(Object.entries(oi.bonus||{}).map(([k,v])=>[k,-v])))}state.equipment[it.slot]=id;eff(it.bonus);showToast(`裝備：${it.name}`)}renderStatus();renderInventory();autoSave()}
function renderInventory(){let eq=Object.values(state.equipment);el.equipmentList.innerHTML=`<div class="equipment-box"><strong>目前裝備</strong><br><small>${eq.length?eq.map(x=>items[x].name).join('・'):'尚未裝備任何物品'}</small></div>`;el.inventoryList.innerHTML=state.inventory.map(id=>{let i=items[id],equipped=Object.values(state.equipment).includes(id);return `<div class="item-card"><strong>${esc(i.name)}</strong><small>${esc(i.desc)}</small>${i.type==='equipment'?`<button class="item-btn" data-equip="${id}">${equipped?'卸下':'裝備'}</button>`:''}</div>`}).join('')||'<div class="item-card">行囊是空的。</div>';el.inventoryList.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.equip))}
function finish(id){let e=endings[id];state.finished=true;state.ending=id;autoSave();showScreen('ending');el.endingTitle.textContent=e.title;el.endingText.textContent=e.text;el.endingStats.innerHTML=`<span>壓力<b>${state.stress}</b></span><span>聲望<b>${state.rep}</b></span><span>疑心<b>${state.suspicion}</b></span>`;scrollTo({top:0,behavior:'smooth'})}function renderLog(){el.logList.innerHTML=state.log.map(x=>`<div class="log-entry"><b>${esc(x.title)}</b><br>${esc(x.text)}</div>`).join('')}function save(){if(!state)return showToast('沒有可保存的進度');autoSave();showToast('進度已保存在此裝置')}function autoSave(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(_){}}function load(){try{state=JSON.parse(localStorage.getItem(SAVE_KEY))}catch(_){state=null}if(!state)return showToast('找不到新版存檔');closeMenu();state.finished?finish(state.ending):renderScene();showToast('已讀取存檔')}function restart(){if(!confirm('要放棄目前進度並回到開始畫面嗎？'))return;state=null;selectedBg=null;el.nameInput.value='';[...el.backgroundChoices.querySelectorAll('.bg-choice')].forEach(b=>b.classList.remove('selected'));el.startBtn.disabled=true;closeMenu();showScreen('start')}function showScreen(w){el.startScreen.classList.toggle('hidden',w!=='start');el.gameScreen.classList.toggle('hidden',w!=='game');el.endingScreen.classList.toggle('hidden',w!=='ending')}function openMenu(){el.menu.classList.remove('hidden');el.backdrop.classList.remove('hidden')}function closeMenu(){el.menu.classList.add('hidden');el.backdrop.classList.add('hidden')}
el.backgroundChoices.onclick=e=>{let b=e.target.closest('.bg-choice');if(!b)return;selectedBg=b.dataset.bg;[...el.backgroundChoices.querySelectorAll('.bg-choice')].forEach(x=>x.classList.toggle('selected',x===b));el.startBtn.disabled=false};el.startBtn.onclick=()=>{state=newState(el.nameInput.value,selectedBg);autoSave();renderScene()};el.loadStartBtn.onclick=load;el.saveBtn.onclick=save;el.inventoryBtn.onclick=()=>{renderInventory();el.inventoryPanel.classList.toggle('hidden');el.logPanel.classList.add('hidden')};el.closeInventoryBtn.onclick=()=>el.inventoryPanel.classList.add('hidden');el.logBtn.onclick=()=>{renderLog();el.logPanel.classList.toggle('hidden');el.inventoryPanel.classList.add('hidden')};el.closeLogBtn.onclick=()=>el.logPanel.classList.add('hidden');el.restartBtn.onclick=restart;el.againBtn.onclick=restart;el.menuBtn.onclick=openMenu;el.menuClose.onclick=closeMenu;el.backdrop.onclick=closeMenu;el.menuSave.onclick=save;el.menuLoad.onclick=load;el.menuRestart.onclick=restart;})();