(()=>{'use strict';
const SAVE_KEY='mist-taiwan-case-save-v2';
const $=id=>document.getElementById(id);
const roles={student:{label:'學生'},worker:{label:'工人'},clerk:{label:'公務員'},reporter:{label:'記者'},teacher:{label:'教師'},merchant:{label:'商人'},veteran:{label:'退伍軍人'},homemaker:{label:'持家者'}};
const evidence={missing_index:{name:'缺頁編號',type:'筆記',desc:'訪談冊缺少第 17、21、22 頁，裝訂處留下相連的斜裂痕。'},print_ledger:{name:'鉛字盒借用簿',type:'帳目',desc:'阿川十二日借出鉛字盒，歸還欄卻記在十三日。'},waste_route:{name:'廢紙去向',type:'情報',desc:'印刷行的廢紙固定交給市場跑腿少年帶走。'},wrapped_scrap:{name:'包花生的紙角',type:'紙片',desc:'市場找到帶有阿川筆跡與「夜班」字樣的紙角。'},runner_account:{name:'少年說法',type:'證詞',desc:'少年把較完整、寫滿字的紙交給舊書攤老闆。'},archive_pages:{name:'三頁失落筆記',type:'關鍵證物',desc:'舊字典裡找到第 17、21、22 頁，裂痕與原冊缺口吻合。'},postal_stub:{name:'錯投郵件存根',type:'存根',desc:'能解釋市場裡郵務人員四處問地址的原因，與阿川無關。'},consent_note:{name:'頁邊鉛筆註記',type:'文字線索',desc:'第 21 頁寫著：「秋月：不要真名。」'}};
const people={achuan:{name:'阿川',desc:'你的舊同學，正在整理訪談紀錄。'},zhou:{name:'周老闆',desc:'印刷行老闆，起初對日期與廢紙去向說得含糊。'},runner:{name:'跑腿少年',desc:'替市場攤商搬貨，也替印刷行帶走廢紙。'},bookseller:{name:'舊書攤老闆',desc:'習慣把仍可使用、寫過字的紙夾進舊書保存。'}};
const locations={tea:{name:'茶行',sub:'案件起點',intro:'茶行快打烊了。阿川把缺了三頁的訪談冊推到你面前。',actions:['tea_index','tea_ask','tea_compare']},print:{name:'印刷行',sub:'油墨與紙堆',intro:'機器剛停，空氣裡仍有油墨味。周老闆正在整理鉛字與紙張。',actions:['print_ledger','print_zhou','print_waste','print_role']},market:{name:'市場',sub:'貨聲與傳言',intro:'攤販、搬貨與叫賣聲混在一起。紙在這裡可能被當成包裝，也可能被隨手轉給別人。',actions:['market_stalls','market_runner','market_postman','market_role']},bookstall:{name:'舊書攤',sub:'紙頁之間',intro:'騎樓深處堆著一排排舊書。幾本工具書的書頁已經發脆。',actions:['book_search','book_owner','book_stub','book_pages']}};
let state=null,selectedRole=null,currentTab='scene';
function freshState(name,role){return{name:(name||'無名調查者').trim(),role,caseId:'case1',location:'tea',unlocked:['tea'],visited:['tea'],evidence:[],people:[],done:[],flags:{actionResults:{}},focus:5,deductionStep:0,finished:false,history:[]}}
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(_){}}
function load(){try{const v=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');return v&&v.caseId==='case1'?v:null}catch(_){return null}}
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__caseToast);window.__caseToast=setTimeout(()=>t.classList.remove('show'),1800)}
function unlock(id){if(!state.unlocked.includes(id))state.unlocked.push(id)}
function gain(id){if(!state.evidence.includes(id)){state.evidence.push(id);toast('新增證物：'+evidence[id].name)}}
function know(id){if(!state.people.includes(id))state.people.push(id)}
function has(id){return state.evidence.includes(id)}
function markDone(id,lines){if(!state.done.includes(id))state.done.push(id);state.flags.actionResults[id]=lines}
const actions={
tea_index:{label:'檢查缺頁位置',run(){gain('missing_index');return['你把冊子攤平，沿裝訂處一頁頁摸過去。第 17、21、22 頁不見了，缺口像是幾張一起被抽走。','你把頁碼記進案件筆記。'];}},
tea_ask:{label:'詢問阿川最後在哪裡使用筆記',run(){know('achuan');unlock('print');return['阿川想了一會兒，說前一晚曾帶著冊子到印刷行排字。','他記得離開時把紙塞回布袋，卻不能確定失頁當時是否仍在冊子裡。印刷行被標進地圖。'];}},
tea_compare:{label:'翻閱缺口前後的內容',run(){return state.role==='student'?['你把第 16 與 18 頁並排。第 16 頁談到工廠夜班，第 18 頁卻已跳到另一段訪談。','你在旁邊記下：第 17 頁很可能仍屬於夜班那段內容。']:['第 16 頁在一段工廠訪談中停住，第 18 頁已換了話題。','你在缺口旁畫了一個問號。'];}},
print_ledger:{label:'查看櫃檯旁的借物簿',run(){gain('print_ledger');return state.role==='clerk'?['你先看欄位而不是內容。借出日期是十二日，歸還卻記在十三日，而且墨色一致。','阿川把時間記錯了一天。']:['借物簿裡找到阿川的名字：十二日借出，十三日才歸還。','至少有一件事可以確定——他的時間記憶並不完全準確。'];}},
print_zhou:{label:'追問周老闆那晚的情況',run(){know('zhou');if(has('print_ledger')){gain('waste_route');unlock('market');state.flags.zhouCracked=true;return['你把借物簿轉向周老闆，指著十三日的歸還紀錄。','他沉默片刻，承認阿川隔天確實又回來過。當天收桌時，他也把一捆廢紙交給市場跑腿少年帶走。','市場被標進地圖。'];}return['周老闆只說那晚人多、事情雜，他記不得阿川留下過什麼。','他的回答沒有矛盾，但也沒有讓你前進。也許先找一件能固定日期的東西。'];}},
print_waste:{label:'檢查後間廢紙堆',run(){return state.flags.zhouCracked?['靠牆的廢紙少了一捆，空位大小和周老闆描述的差不多。','這不能證明失頁一定在裡面，但紙確實有一條通往市場的日常路徑。']:['廢紙整齊捆在牆邊，其中一處留下空位。','你問少掉的那捆去哪裡，周老闆只回了一句：「早就處理掉了。」'];}},
print_role:{label:'從自己的身分切入',special:true,run(){const t={student:['你翻看校刊尺寸的試印紙，周老闆見你認得版式，承認阿川確實在這裡排過訪談標題。'],worker:['你幫忙把紙捆搬到牆邊。周老闆順口提起，市場那個跑腿少年常來拿廢紙。'],clerk:['你比對前後幾筆借物紀錄，沒有發現補寫或跳號。'],reporter:['你改問「最後一個碰桌面的人是誰」，周老闆回答是他自己。'],teacher:['你提到阿川整理的是訪談，不是要公開的傳單。周老闆的語氣稍微鬆了一些。'],merchant:['你先問廢紙平常怎麼處理。周老闆說量不多，通常直接讓市場少年帶走。'],veteran:['你沒有把周老闆的停頓當成證據，只記下「阿川來過」與「失頁去向未知」兩件事。'],homemaker:['你注意到後間有市場攤販用的粗麻繩與空竹籃。周老闆承認附近商販常來拿廢紙墊箱。']};return t[state.role]||['你換了一個熟悉的角度觀察現場，但暫時沒有新的結論。'];}},
market_stalls:{label:'沿攤位尋找被拿來包貨的紙',run(){gain('wrapped_scrap');return['你在菜葉、麻繩與包裝紙間慢慢翻找，最後從花生攤腳邊抽出一角較白的紙。','紙上只剩半句字，末尾卻清楚寫著「夜班」。筆跡與阿川的冊子一致。'];}},
market_runner:{label:'詢問跑腿少年那捆廢紙',run(){know('runner');if(has('wrapped_scrap')||['worker','teacher'].includes(state.role)){gain('runner_account');unlock('bookstall');return['少年看過紙角後想起來了。那捆紙大多被拿去墊箱，幾張完整、又寫滿字的紙則被他交給舊書攤老闆。','舊書攤被標進地圖。'];}return['少年搖頭，說每天搬的東西太多，想不起是哪一捆。','你需要更具體的紙張或更能讓他想起那天的問法。'];}},
market_postman:{label:'追查「有人四處問地址」的傳言',run(){state.flags.postmanRumor=true;return['幾名攤販都記得昨天有個穿郵務制服的人反覆問地址。','但「他在找阿川」這句話沒有人能說出是從哪裡聽來的。你把它標成未證實。'];}},
market_role:{label:'從自己的身分切入',special:true,run(){const t={student:['你把紙角上的「夜班」與第 16 頁內容比對，語句結構十分接近。'],worker:['你幫少年搬完兩箱貨，他主動提到曾把幾張完整紙送去舊書攤。'],clerk:['三個攤販都說廢紙每兩三天會來一次，流向相當固定。'],reporter:['你分開詢問三個攤販。只有「郵務制服」和「問地址」能被多方證實。'],teacher:['少年先把你當成老師，回答時反而願意把那天的事情重新想一遍。'],merchant:['你問的是哪些攤位會用印刷廢紙，很快拼出墊箱、包貨、剩下完整紙張的流向。'],veteran:['你把「看到郵務人員」與「郵務人員在找阿川」分成兩條記錄。後者目前沒有直接證詞。'],homemaker:['你先從攤販日常聊起，舊書攤老闆「有字的完整紙會留下」的習慣自然被提了出來。']};if(['worker','teacher','merchant','homemaker'].includes(state.role))unlock('bookstall');return t[state.role]||['你換了一個熟悉的角度觀察市場。'];}},
book_search:{label:'翻找可能夾過紙的舊工具書',run(){if(!has('runner_account')&&state.role!=='student')return['你翻了幾本字典與簿冊，只找到舊收據和空白紙。','範圍太大。若能先知道少年把紙交給老闆時的情況，會比較容易縮小。'];gain('archive_pages');return['你逐本翻過幾本最常被拿來夾紙的工具書。一本破字典中段明顯厚了一截。','三張摺過的紙滑出來：17、21、22。裂痕與阿川冊上的缺口正好接回去。'];}},
book_owner:{label:'詢問老闆紙張來源',run(){know('bookseller');return has('runner_account')?['老闆很快想起那名少年。「他說拿來包東西太可惜，我就先夾著。」','這和少年的說法一致。']:['老闆說有些寫滿字的紙是市場跑腿少年塞給他的。','你把這件事記下來。'];}},
book_stub:{label:'檢查櫃檯下的舊存根',run(){gain('postal_stub');return state.flags.postmanRumor?['你找到一張錯投郵件存根。老闆想起昨天那名郵務人員是在找一封送錯市場巷口的信。','存根地址與阿川、印刷行都無關。那條傳言有了一個普通得多的解釋。']:['你找到一張錯投郵件存根。老闆說昨天確實有郵務人員來確認地址。','地址與阿川、印刷行都無關。'];}},
book_pages:{label:'仔細閱讀找回的三頁',run(){if(!has('archive_pages'))return['三頁還沒找到。你現在能讀的只有架上的舊書。'];gain('consent_note');state.flags.deductionReady=true;return['你把三頁按頁碼排好。第 21 頁右側有一行很淡的鉛筆字：「秋月：不要真名。」','紙已找回，但另一個問題浮了出來。推理頁面現在可以進行結案。'];}}
};
const deduction=[{q:'第一問：三頁失頁最可能怎麼離開印刷行？',opts:[['steal','有人趁周老闆不注意偷走'],['waste','整理時混進廢紙，被一起帶去市場'],['achuan','阿川故意交給陌生人']],correct:'waste',need:'wrapped_scrap'},{q:'第二問：市場裡的郵務人員與失頁有什麼關係？',opts:[['tracker','他在追查阿川筆記'],['unknown','應先把他當主要嫌疑人'],['postal','他在處理錯投郵件，沒有證據與失頁有關']],correct:'postal',need:'postal_stub'},{q:'第三問：哪件證物能直接確認找回的紙就是原失頁？',opts:[['ledger','鉛字盒借用簿'],['pages','三頁失落筆記本身'],['runner','少年說法']],correct:'pages',need:'archive_pages'}];
function renderFocus(){const box=$('focusDots');box.innerHTML='';for(let i=0;i<5;i++){const d=document.createElement('i');if(i<state.focus)d.classList.add('on');box.appendChild(d)}}
function showGame(){['startScreen','completeScreen'].forEach(id=>$(id).classList.add('hidden'));$('gameScreen').classList.remove('hidden');$('playerLabel').textContent=`${state.name}・${roles[state.role].label}`;renderFocus();setTab(currentTab)}
function setTab(tab){currentTab=tab;document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const panels={scene:'scenePanel',map:'mapPanel',record:'recordPanel',deduction:'deductionPanel'};Object.values(panels).forEach(id=>$(id).classList.add('hidden'));$(panels[tab]||panels.scene).classList.remove('hidden');if(tab==='scene')renderScene();if(tab==='map')renderMap();if(tab==='record')renderRecords();if(tab==='deduction')renderDeduction()}
function appendLines(lines){const box=$('sceneBody');box.innerHTML='';lines.forEach(t=>{const p=document.createElement('p');p.textContent=t;box.appendChild(p)})}
function renderScene(){const loc=locations[state.location];$('locationName').textContent=loc.name;$('locationSub').textContent=loc.sub;const last=state.flags.lastResult;appendLines(last&&last.location===state.location?last.lines:[loc.intro]);const grid=$('actionGrid');grid.innerHTML='';loc.actions.forEach(id=>{const a=actions[id],b=document.createElement('button');b.className='action-btn';if(a.special)b.classList.add('special');const wasDone=state.done.includes(id);if(wasDone)b.classList.add('done');b.innerHTML=`<strong>${a.label}</strong><small>${wasDone?'已調查，可再次查看':'進行調查'}</small>`;b.onclick=()=>runAction(id);grid.appendChild(b)})}
function runAction(id){const a=actions[id];let lines;if(state.done.includes(id)&&state.flags.actionResults[id])lines=state.flags.actionResults[id];else{lines=a.run()||['你沒有找到新的東西。'];markDone(id,lines)}state.flags.lastResult={location:state.location,lines};state.history.push({type:'action',location:state.location,id});save();renderScene()}
function renderMap(){const grid=$('mapGrid');grid.innerHTML='';Object.entries(locations).forEach(([id,l])=>{const unlocked=state.unlocked.includes(id),b=document.createElement('button');b.className='map-btn'+(state.visited.includes(id)?' visited':'')+(unlocked?'':' locked');b.disabled=!unlocked;b.innerHTML=`<strong>${l.name}</strong><small>${unlocked?l.sub:'尚未取得前往線索'}</small>`;b.onclick=()=>{state.location=id;if(!state.visited.includes(id))state.visited.push(id);state.flags.lastResult=null;save();setTab('scene')};grid.appendChild(b)})}
function renderRecords(){const ev=$('evidenceGrid'),pp=$('peopleGrid');ev.innerHTML='';pp.innerHTML='';if(!state.evidence.length)ev.innerHTML='<div class="evidence-card"><strong>尚無證物</strong><small>調查後取得的物件與情報會收在這裡。</small></div>';state.evidence.forEach(id=>{const e=evidence[id],d=document.createElement('div');d.className='evidence-card';d.innerHTML=`<strong>${e.name}</strong><small>${e.desc}</small><span class="tag">${e.type}</span>`;ev.appendChild(d)});if(!state.people.length)pp.innerHTML='<div class="person-card"><strong>尚無人物紀錄</strong><small>交談後會加入相關人物。</small></div>';state.people.forEach(id=>{const p=people[id],d=document.createElement('div');d.className='person-card';d.innerHTML=`<strong>${p.name}</strong><small>${p.desc}</small>`;pp.appendChild(d)});$('evidenceCount').textContent=state.evidence.length}
function loseFocus(msg){state.focus=Math.max(0,state.focus-1);state.flags.deductionFeedback=msg;if(state.focus===0){state.focus=2;state.flags.deductionFeedback+=' 你停下來重新整理紀錄，思路稍微恢復。'}save();renderFocus();renderDeduction()}
function renderDeduction(){const box=$('deductionBox');box.innerHTML='';if(!state.flags.deductionReady){box.innerHTML='<h2>推理尚未開放</h2><p>至少先找到三頁失落筆記並仔細閱讀。</p>';return}const step=deduction[state.deductionStep];if(!step){finishCase();return}box.innerHTML=`<h2>${step.q}</h2><p>選出你的推論；答對後還要提出能支撐它的證物。</p>`;const opts=document.createElement('div');opts.className='deduction-options';step.opts.forEach(([id,label])=>{const b=document.createElement('button');b.className='deduction-option';b.innerHTML=`<strong>${label}</strong>`;b.onclick=()=>{if(id!==step.correct){loseFocus('這個說法把尚未證實的部分當成事實。');return}renderEvidencePicker(step)};opts.appendChild(b)});box.appendChild(opts);if(state.flags.deductionFeedback){const f=document.createElement('div');f.className='feedback';f.textContent=state.flags.deductionFeedback;box.appendChild(f)}}
function renderEvidencePicker(step){const box=$('deductionBox');box.innerHTML='<h2>提出證物</h2><p>哪一件你已取得的證物，最能支撐剛才的推論？</p>';const opts=document.createElement('div');opts.className='deduction-options';state.evidence.forEach(id=>{const e=evidence[id],b=document.createElement('button');b.className='deduction-option';b.innerHTML=`<strong>${e.name}</strong><small>${e.type}</small>`;b.onclick=()=>{if(id!==step.need){loseFocus('這件證物無法直接支撐剛才的推論。');return}state.deductionStep++;state.flags.deductionFeedback='';save();toast('推理成立');renderDeduction()};opts.appendChild(b)});box.appendChild(opts)}
function finishCase(){state.finished=true;save();$('gameScreen').classList.add('hidden');$('completeScreen').classList.remove('hidden');const box=$('completeText');box.innerHTML='';['你把三頁紙按頁碼放回阿川面前。它們不是被誰刻意偷走，而是在印刷行整理時混進廢紙，跟著跑腿少年到了市場，最後被舊書攤老闆夾進破字典。','市場裡四處問地址的郵務人員只是另一件普通事件，沒有證據和失頁相連。','阿川看見第 21 頁邊上的鉛筆字：「秋月：不要真名。」第一案結束，下一個問題卻才剛開始。'].forEach(t=>{const p=document.createElement('p');p.textContent=t;box.appendChild(p)})}
function restart(){localStorage.removeItem(SAVE_KEY);location.reload()}
window.addEventListener('DOMContentLoaded',()=>{const roleGrid=document.querySelector('.role-grid');roleGrid.addEventListener('click',e=>{const b=e.target.closest('.role-btn');if(!b)return;selectedRole=b.dataset.role;document.querySelectorAll('.role-btn').forEach(x=>x.classList.toggle('selected',x===b));$('startBtn').disabled=false});$('startBtn').addEventListener('click',()=>{if(!selectedRole)return;state=freshState($('nameInput').value,selectedRole);save();currentTab='scene';showGame()});$('loadBtn').addEventListener('click',()=>{const s=load();if(!s){toast('找不到案件存檔');return}state=s;currentTab='scene';showGame()});document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));$('recordEvidenceBtn').addEventListener('click',()=>{$('evidenceSection').classList.remove('hidden');$('peopleSection').classList.add('hidden');$('recordEvidenceBtn').classList.add('active');$('recordPeopleBtn').classList.remove('active')});$('recordPeopleBtn').addEventListener('click',()=>{$('peopleSection').classList.remove('hidden');$('evidenceSection').classList.add('hidden');$('recordPeopleBtn').classList.add('active');$('recordEvidenceBtn').classList.remove('active')});$('restartBtn').addEventListener('click',()=>{if(confirm('確定重新開始案件？目前案件存檔會被清除。'))restart()});$('legacyLink').addEventListener('click',()=>{location.href='legacy.html'});$('nextCaseBtn').addEventListener('click',()=>toast('案件二正在製作：秋月的條件'));$('loadBtn').disabled=!load()});
})();