(()=>{'use strict';
const SAVE_KEY='mist-taiwan-rpg-save-v4',OLD_KEYS=['mist-taiwan-rpg-save-v3','mist-taiwan-rpg-save-v2'];
const roles={
 student:{label:'學生',passive:'求知',desc:'閱讀、校園與學術場合更容易理解額外資訊。',stats:{insight:2,knowledge:2,composure:0,rapport:0},items:['student_id','notebook']},
 worker:{label:'工人',passive:'同袍',desc:'與工人、搬運者與勞動現場人物互動時更容易建立信任。',stats:{insight:0,knowledge:0,composure:2,rapport:2},items:['work_gloves','meal_ticket']},
 clerk:{label:'公務員',passive:'熟悉體制',desc:'較能讀懂公文、行政流程與制度留下的線索。',stats:{insight:0,knowledge:1,composure:1,rapport:2},items:['fountain_pen','document_bag']},
 reporter:{label:'記者',passive:'新聞嗅覺',desc:'容易察覺矛盾與可追查的消息，但部分人物會因此更加戒備。',stats:{insight:2,knowledge:1,composure:0,rapport:1},items:['reporter_notes','camera']},
 teacher:{label:'教師',passive:'為人師表',desc:'學生、家長與部分知識分子較容易把你視為可信任的談話對象。',stats:{insight:0,knowledge:2,composure:0,rapport:2},items:['teacher_id','old_dictionary']},
 merchant:{label:'商人',passive:'生意人',desc:'市場、價格、帳目與人情交換相關事件有額外處理方式。',stats:{insight:0,knowledge:0,composure:1,rapport:3},items:['ledger','coin_purse']},
 veteran:{label:'退伍軍人',passive:'戰地經驗',desc:'面對戰事消息與突發緊張時更能保持鎮定。',stats:{insight:1,knowledge:0,composure:3,rapport:0},items:['army_bag','veteran_card']},
 homemaker:{label:'持家者',passive:'街坊消息',desc:'市場、鄰里與家庭場合較容易聽見被忽略的日常資訊。',stats:{insight:1,knowledge:0,composure:1,rapport:2},items:['household_book','cloth_bag']}
};
const items={
 student_id:{name:'學生證',desc:'證明學生身分；校園與書店場合可能派上用場。',type:'tool'},
 notebook:{name:'袖珍筆記本',desc:'可整理零碎線索。',type:'equipment',slot:'pocket',bonus:{insight:1}},
 work_gloves:{name:'舊工作手套',desc:'粗厚耐用，帶著工廠生活留下的痕跡。',type:'equipment',slot:'hand',bonus:{composure:1}},
 meal_ticket:{name:'工廠餐券',desc:'一張尚未使用的餐券。',type:'consumable'},
 fountain_pen:{name:'鋼筆',desc:'一支體面的鋼筆，適合記錄與公務場合。',type:'equipment',slot:'hand',bonus:{rapport:1}},
 document_bag:{name:'公文袋',desc:'習慣用來整理文件的硬紙袋。',type:'tool'},
 reporter_notes:{name:'記者筆記',desc:'頁角密密寫著日期、姓名與待查事項。',type:'equipment',slot:'pocket',bonus:{insight:1}},
 camera:{name:'底片相機',desc:'能在特定事件留下影像紀錄。',type:'tool'},
 teacher_id:{name:'教職證明',desc:'證明你的教師身分。',type:'tool'},
 old_dictionary:{name:'缺頁字典',desc:'一本舊字典，夾層適合保存紙張。',type:'equipment',slot:'pocket',bonus:{knowledge:1}},
 ledger:{name:'商用帳本',desc:'熟悉的帳目格式能幫助你看出數字中的異常。',type:'tool'},
 coin_purse:{name:'零錢包',desc:'做生意養成隨身準備零錢的習慣。',type:'tool'},
 army_bag:{name:'舊軍用背包',desc:'退伍後仍留下的耐用背包。',type:'equipment',slot:'bag',bonus:{composure:1}},
 veteran_card:{name:'退伍證明',desc:'一張收得很平整的退伍證明。',type:'tool'},
 household_book:{name:'家庭帳簿',desc:'柴米油鹽與每月支出都記得清楚。',type:'tool'},
 cloth_bag:{name:'布提袋',desc:'買菜、跑腿與裝雜物都很實用。',type:'equipment',slot:'bag',bonus:{rapport:1}},
 matchbox:{name:'茶行火柴盒',desc:'盒底寫著一個印刷行地址。',type:'tool'},
 archive_pages:{name:'三頁失落筆記',desc:'阿川遺失的訪談與觀察紀錄。',type:'quest'},
 postal_stub:{name:'郵件存根',desc:'一張能證明某封信曾被錯投的存根。',type:'quest'},
 print_receipt:{name:'印刷收據',desc:'記有日期、紙張數量與借物紀錄。',type:'quest'},
 family_note:{name:'秋月家的藥費單',desc:'一張普通的藥費單，卻讓家庭壓力變得具體。',type:'quest'}
};
const passiveText={
 intro:{student:'你先注意到紙張和筆跡，想起校內那些靠手抄流傳的小冊子。',worker:'你才從工作回來，手上的疲憊讓你更在意：有人為何非得今晚把信送到住處。',clerk:'你每天都看格式完整的文件，因此更快注意到這封信刻意沒有日期、地址與寄件人。',reporter:'你本能地先看紙張、筆跡與措辭；它不像新聞線索，更像一個不想留下來源的人在求助。',teacher:'你批改過太多文字，知道一句話有時會暴露比寫信的人預期更多的情緒。',merchant:'你習慣估量代價。這封信沒有談錢，也沒有說明回報，反而更難判斷。',veteran:'你曾學會在資訊不足時不要急著下判斷。短短一句「別向別人提起」讓你先把信收好。',homemaker:'街坊每天都有消息流動，但真正重要的事往往說得最小聲；這封信的語氣讓你想起最近幾次欲言又止的鄰里談話。'},
 tea_shop:{student:'阿川提到校園生活時，你很快分得出哪些只是普通抱怨，哪些是需要更多上下文才不會被誤讀的話。',worker:'他提到工廠訪談時，你不必靠想像理解夜班、薪資與受傷後仍得上工是什麼意思。',clerk:'你注意到他的筆記沒有固定編號與日期欄位，這讓「遺失三頁」變得比想像中更難追。',reporter:'你立刻想到來源保護與受訪者同意；阿川顯然沒有完全想過記錄被第三人取得後會發生什麼。',teacher:'你對「留下學生與工人的聲音」並不反感，但更在意被記錄的人是否真的理解文字會被保存多久。',merchant:'你看出這件事沒有清楚的成本邊界：時間、信任與人情都可能在過程中被消耗。',veteran:'阿川的焦躁很明顯。你知道人在緊張時容易把每個巧合都連成一條線。',homemaker:'你最先想到的不是紙，而是紙上的人。如果真有家庭地址或姓名，麻煩可能落到完全沒參與的人身上。'},
 print_shop:{student:'牆邊幾疊校刊尺寸的紙張先吸引你的目光，你認得其中一些排版習慣。',worker:'你先注意到搬紙留下的磨痕與角落堆放方式；這裡每天移動的東西比嘴上說的多。',clerk:'帳簿欄位與收據擺法讓你很熟悉。周老闆說得含糊，店裡的紀錄卻未必如此。',reporter:'你掃過日期、紙張來源與桌上的名字；周老闆也很快看出你不是普通來客，語氣因此更保守。',teacher:'幾張試印紙上有常見教材用字，你知道這種小印刷行與學校、社團往來頻繁。',merchant:'你看得出周老闆正在趕幾筆生意；在生意人最忙時問私人問題，通常不是好時機。',veteran:'你沒有把他的停頓當成證據。經驗告訴你，緊張和隱瞞不是同一回事。',homemaker:'你注意到後間有人剛送過茶，櫃檯旁還放著鄰近店家的碗盤，這間店和附近街坊的關係比表面更密。'},
 market:{student:'攤販交換消息的速度比校園還快，但你也知道傳得快不代表準確。',worker:'搬貨的人和你說話時少了些客套；工作留下的姿態與手掌，有時比自我介紹更快。',clerk:'攤商抱怨送貨、票據與公家規定，你熟悉的制度在這裡變成每個人的生活成本。',reporter:'每個攤位似乎都有一個版本的故事；你的工作提醒你，消息多不等於真相近。',teacher:'幾個替家裡跑腿的孩子聽出你的說話方式像老師，回答時不自覺站得更直。',merchant:'你不用刻意打聽就能聽懂進貨與價格，誰和誰熟、貨從哪來，常藏在討價還價裡。',veteran:'戰事新聞讓市場議論更緊繃，你聽得出哪些是親身消息，哪些只是轉述。',homemaker:'你熟悉這種地方的節奏；直接盤問反而不如先聽買米、賣菜與排隊的人怎麼談昨天。'},
 bookstall:{student:'書攤的分類方式讓你很快發現那本字典被刻意放在與其他工具書不同的位置。',worker:'你注意到老闆把那幾張紙壓得很平整，顯然不是隨手留下的廢紙。',clerk:'你先檢查頁面順序與日期，三頁並非連續頁，表示阿川可能還有其他缺漏。',reporter:'你先問老闆「誰看過這三頁」，而不是只問紙本身；來源接觸鏈對你而言和內容同樣重要。',teacher:'字典中的夾頁讓你想到學生常用的藏紙方法，也提醒你紙張本身未必是最安全的保存方式。',merchant:'你看出老闆沒有打算把紙當商品賣；他留下它純粹是因為覺得不尋常。',veteran:'你先確認是否有人急著追問這些紙，而不是把「有人問過」直接當成威脅。',homemaker:'老闆提起跑腿少年時語氣熟稔，你判斷這條線索仍然屬於街坊日常網絡，而不一定意味著更大的事情。'},
 professor:{student:'你能跟上教授談資料分類與來源可信度的思路，並開始把阿川的筆記當成一份需要方法的材料。',worker:'教授的話很抽象，但你一直想到紙上那些具體的人：名字被留下，承擔後果的卻是他們。',clerk:'把姓名、單位與內容分開保存的做法，讓你想到公文中的分卷與索引，這方法對你並不陌生。',reporter:'你熟悉匿名、來源保護與查證之間的拉扯，也看出阿川之前把「記錄」和「公開」想得太接近。',teacher:'教授談到未來讀者時，你想到的是學生：留下材料，不代表能省略如何解讀材料的責任。',merchant:'你把整件事理解成風險分散：不是什麼都丟掉，也不是什麼都放在同一處。',veteran:'你在意的是最壞情況下誰會承擔後果，因此更支持把可辨識資訊減到必要程度。',homemaker:'你立刻理解把家庭地址與訪談內容分開的價值；真正不該被捲入的人，往往是同住的家人。'},
 factory_branch:{student:'機器聲比你想像得更難讓人集中精神，筆記裡簡短的「夜班」兩字突然有了重量。',worker:'你幾乎不必解釋自己為何理解輪班與工傷，工友看你的眼神也和看一般訪客不同。',clerk:'你注意到出勤、請假與名冊都有固定格式，但紙面紀錄未必能說明一個人為何沒來上班。',reporter:'你很清楚訪談可以留下故事，也可以讓受訪者感到被暴露；你的記者身分因此變得敏感。',teacher:'「弟妹的學費」讓你停了一下，你見過學生因家庭收入改變而突然缺課。',merchant:'你從貨車與交貨節奏看見另一種帳目：每次缺勤與延誤最後都會變成成本。',veteran:'規律的機器聲讓你想起另一種集體生活，但你提醒自己不要拿自己的經歷替秋月解釋她的處境。',homemaker:'你最先在意的不是缺勤，而是「父親病倒」後家裡還有誰能照顧、誰得出去工作。'},
 qiuyue_home:{student:'面對真正的受訪者，你第一次清楚感覺到課堂上談的「資料」其實是別人的生活。',worker:'秋月不需要向你解釋為什麼少一天工資也會讓家裡難受。',clerk:'你開始把「同意」看成一個應該被明確記錄的條件，而不是口頭上的模糊默契。',reporter:'她對你的職業顯然更戒備。你知道此刻最重要的不是得到更多內容，而是讓她能決定哪些話不被使用。',teacher:'談到弟妹時，她的語氣變了；你更容易把她的家庭壓力與孩子的學習處境連在一起。',merchant:'你注意到桌上幾張帳單，比任何抽象描述都更清楚地顯示這個家庭承受的壓力。',veteran:'你沒有急著填補她的沉默，因為你知道有些經歷不應該由旁人逼著說完整。',homemaker:'屋裡的藥袋、飯鍋與晾著的衣服讓你先看到這是一個正在撐住日常的家庭，而不是故事裡的一個「角色」。'}
};
const C=(label,next,effects={},extra={})=>({label,next,effects,...extra});
const S=(chapter,location,date,title,text,choices)=>({chapter,location,date,title,text,choices});
const scenes={
intro:S('第一章・雨夜','臺北・大稻埕','1958 年 9 月','一封沒有署名的信',['傍晚的雨把街上的招牌洗得發亮。回到住處，你發現門縫下壓著一封沒有署名的信。','舊同學阿川邀你明晚到茶行見面，只寫著：「別向別人提起。」','你不知道這是一場普通求助，還是某件更大的事情的入口。'],[C('把信收好，明晚赴約','tea_shop',{stress:1}),C('先向共同朋友美惠打聽','ask_friend',{suspicion:1}),C('處理掉信，當作沒有看見','ignored',{composure:1}),C('先從紙張與措辭判斷它像不像校內流傳的手抄信','tea_shop',{knowledge:1},{onlyBg:'student'}),C('把信上的時間與自己上下工的路線對照','ask_friend',{insight:1},{onlyBg:'worker'}),C('檢查它刻意缺少哪些正式書信欄位','ask_friend',{knowledge:1},{onlyBg:'clerk'}),C('把它當成一條未證實線索，先查阿川最近的公開行蹤','ask_friend',{insight:1,suspicion:1},{onlyBg:'reporter'}),C('先想想阿川以前在學校最信任哪些人','ask_friend',{rapport:1},{onlyBg:'teacher'}),C('先問自己：這件事會讓多少人情與時間被牽進來','elder',{composure:1},{onlyBg:'merchant'}),C('不急著判斷威脅，先確認阿川是否真的失聯','ask_friend',{composure:1},{onlyBg:'veteran'}),C('先從街坊口中確認這兩天有沒有看見阿川','ask_friend',{rapport:1},{onlyBg:'homemaker'})]),
ask_friend:S('第一章・雨夜','臺北・城中','1958 年 9 月','美惠的停頓',['美惠聽見阿川的名字時停頓了一瞬。她說阿川最近常往書店與印刷行跑。','「他不是在做壞事，只是太相信留下文字很重要。」她說。'],[C('停止追問，直接去見阿川','tea_shop',{rapport:1}),C('追問印刷行的位置','print_shop',{insight:1,suspicion:1}),C('不問立場，只問他最後一次出現的時間','tea_shop',{insight:1},{onlyBg:'reporter'}),C('順著她熟悉的人際關係慢慢問','tea_shop',{rapport:1},{onlyBg:'homemaker'})]),
ignored:S('第一章・雨夜','臺北・住處','1958 年 9 月','事情沒有因此消失',['兩天後，美惠主動來找你。阿川沒有回家，茶行老闆託她帶來一只火柴盒。','盒底寫著一個地址。你本來想離事情遠一點，但事情卻自己回到門口。'],[C('收下火柴盒，去印刷行','print_shop',{stress:1},{give:'matchbox'}),C('先找可信任的長輩商量','elder',{rapport:1},{give:'matchbox'})]),
elder:S('第二章・旁觀者','臺北・家中','1958 年 9 月','長輩的經驗',['長輩沒有鼓勵你冒險，也沒有要你立刻把東西交出去。','「先弄清楚手上的東西是什麼。不要因害怕替別人定罪，也別因相信朋友忽略風險。」'],[C('依建議去印刷行查證','print_shop',{knowledge:1,composure:1}),C('把界線停在這裡',null,{stress:-1},{ending:'quiet'})]),
tea_shop:S('第二章・暗語','臺北・茶行','1958 年 9 月','茶香裡的委託',['阿川比記憶中疲憊。他正在整理工廠勞動、校園生活與普通人的訪談紀錄，但其中三頁不見了。','那些紙上沒有行動計畫。他真正害怕的，是內容脫離上下文後傷到被記錄的人。'],[C('答應幫忙找回失頁','investigate',{rep:1,stress:1}),C('先閱讀剩餘筆記','read_notes',{knowledge:1}),C('勸他停止，先保全自己','withdraw',{composure:1}),C('先把失頁的頁碼、筆跡與可能出現的地點整理成清單','read_notes',{knowledge:1,insight:1},{onlyBg:'student'}),C('先問清楚工廠訪談是在哪一班、由誰介紹','investigate',{rapport:1},{onlyBg:'worker'}),C('先替他的紀錄補上日期與編號，再確認究竟少了哪些頁','read_notes',{knowledge:1},{onlyBg:'clerk'}),C('先問哪些人看過筆記，建立一條接觸順序','investigate',{insight:1,suspicion:1},{onlyBg:'reporter'}),C('先確認受訪者當時是否知道內容會被保存','professor',{knowledge:1},{onlyBg:'teacher'}),C('先估算找紙需要動用哪些人情，再決定從哪條線查','investigate',{rapport:1,composure:1},{onlyBg:'merchant'}),C('先把「確定的事」和「阿川猜測的事」分開列出來','read_notes',{composure:1,insight:1},{onlyBg:'veteran'}),C('先問紙上有沒有家庭地址、親屬姓名或住家細節','professor',{rapport:1},{onlyBg:'homemaker'})]),
read_notes:S('第二章・暗語','臺北・茶行','1958 年 9 月','紙上的日常',['筆記不像宣言，而是工資、剪報、課堂見聞與訪談。你開始理解：記錄本身沒有單一意義。','茶行老闆看你反覆整理紙張，送你一本小筆記本：「至少別把線索都記在腦子裡。」'],[C('協助找回失頁','investigate',{insight:1},{give:'notebook'}),C('找可信任的學者討論保存方式','professor',{knowledge:1,suspicion:1},{give:'notebook'}),C('依頁面引用的書名反推阿川最近去過哪間書店','bookstall',{knowledge:1},{onlyBg:'student',requires:{knowledge:3}}),C('把每段訪談分成「親見、轉述、推測」','professor',{knowledge:1},{onlyBg:'reporter'})]),
withdraw:S('第二章・暗語','臺北・茶行後巷','1958 年 9 月','退後一步',['阿川沉默很久，最後把資料收回袋子。','你可以就此離開，也可以至少確認他平安回家。'],[C('陪阿川走一段路','investigate',{insight:1,stress:1}),C('就此退出',null,{suspicion:-1},{ending:'quiet'}),C('用自己的經驗讓他先把呼吸與步調放慢','investigate',{composure:1},{onlyBg:'veteran'})]),
investigate:S('第三章・失頁','臺北・街區','1958 年 9 月','三條普通的路',['阿川最後整理資料的地方只有茶行、印刷行與市場。你們決定分開查找。','這不是偵探故事。你能依靠的只是觀察、記憶與別人願不願意相信你。'],[C('先去印刷行','print_shop'),C('先去市場','market',{rapport:1}),C('先去舊書攤看看是否有人收了廢紙','bookstall',{insight:1},{onlyBg:'student'}),C('先從工廠那條訪談線問起','factory_branch',{rapport:1},{onlyBg:'worker'}),C('先按日期順序整理阿川的行程','print_shop',{knowledge:1},{onlyBg:'clerk'}),C('先找能交叉驗證的兩個來源','market',{insight:1},{onlyBg:'reporter'}),C('先問學術圈是否有人看過這類筆記','professor',{knowledge:1},{onlyBg:'teacher'}),C('先從廢紙與印刷品的流向查起','market',{rapport:1},{onlyBg:'merchant'}),C('先排除只是普通遺失的可能','print_shop',{composure:1},{onlyBg:'veteran'}),C('先從茶行、鄰居與市場三邊交叉問消息','market',{rapport:1},{onlyBg:'homemaker'})]),
print_shop:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','油墨與廢紙',['周老闆的桌上堆著喜帖、傳單與帳簿。你提到阿川，他先否認，才反問：「你是找人，還是找紙？」','角落的廢紙簍裡，有半張與阿川筆記相似的紙。'],[C('坦白只想確認阿川與失頁','printer_truth',{rapport:1}),C('不急著說話，先觀察店裡','printer_observe',{insight:1},{requires:{insight:2}}),C('從紙張尺寸判斷哪些可能來自校刊或筆記','printer_observe',{knowledge:1},{onlyBg:'student'}),C('從搬運痕跡判斷廢紙最近是否整批被移走','printer_observe',{insight:1},{onlyBg:'worker'}),C('從帳簿與收據格式找出阿川留下的紀錄','printer_record',{knowledge:1},{onlyBg:'clerk'}),C('以採訪經驗分辨周老闆避開的是哪個問題','printer_reporter',{insight:1,suspicion:1},{onlyBg:'reporter'}),C('用學校印刷需求當話題，先讓對話自然一些','printer_truth',{rapport:1},{onlyBg:'teacher'}),C('先談紙價與最近的生意，再慢慢轉到廢紙流向','printer_truth',{rapport:1},{onlyBg:'merchant'}),C('不把他的緊張當成有罪，先問能確認的事','printer_truth',{composure:1},{onlyBg:'veteran'}),C('先從送茶與附近店家的人情關係問起','printer_truth',{rapport:1},{onlyBg:'homemaker'})]),
printer_observe:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','被撕掉的一角',['你看見借物清單上寫著「川：鉛字盒一只」。周老闆確實認識阿川。','你沒有立刻揭穿他，而是把這件事記在心裡。'],[C('用線索換取實話','printer_truth',{rep:1}),C('把這條紀錄抄進筆記，先不逼問','market',{insight:1},{onlyBg:'student'})]),
printer_record:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','帳簿裡的時間',['你很快找到一筆格式異常的借物紀錄：阿川借走鉛字盒的日期，比他自己記得的晚一天。','這不能證明什麼，卻表示他的行程記憶並不可靠。周老闆見你看懂帳簿，也不再完全否認。'],[C('請周老闆把那筆紀錄說完整','printer_truth',{rep:1},{give:'print_receipt'}),C('只抄日期，不追問私人內容','market',{composure:1},{give:'print_receipt'})]),
printer_reporter:S('第三章・鉛字','臺北・印刷行','1958 年 9 月','問題中的空白',['你故意把「找人」和「找紙」分開問。周老闆對阿川本人並不迴避，真正讓他停頓的是「那三頁寫了什麼」。','這表示他的顧慮更像內容風險，而不是阿川的去向。你的職業也讓他更小心措辭。'],[C('明說你不會把他的話當成公開消息','printer_truth',{rapport:1,suspicion:-1}),C('不再追問，先查廢紙去向','market',{insight:1})]),
printer_truth:S('第三章・失頁','臺北・印刷行後間','1958 年 9 月','廢紙去了市場',['周老闆承認阿川來過。三頁紙可能混進一疊廢紙，被一名替市場跑腿的少年帶走。','他還塞給你一張工廠餐券：「那孩子常餓著肚子跑腿，別一開口就盤問人家。」'],[C('前往市場','market',{rapport:1},{give:'meal_ticket'}),C('先把日期與廢紙批次記清楚再走','market',{knowledge:1},{onlyBg:'clerk',give:'meal_ticket'}),C('問清楚那批紙平常賣給誰','market',{rapport:1},{onlyBg:'merchant',give:'meal_ticket'})]),
market:S('第四章・市場','臺北・市場','1958 年 9 月','一張包過花生的紙',['市場只在意魚價、雨勢與今天能不能把貨賣完。跑腿少年承認拿過一疊廢紙，其中幾張包過花生，其餘送到舊書攤。','他說昨天也有人問過「印著奇怪文字的紙」。你不知道那代表什麼。'],[C('直接去舊書攤','bookstall',{stress:1}),C('耐心問清楚昨天那個人','uniform',{insight:1},{requires:{rapport:2}}),C('把餐券送給少年，再請他回想','uniform',{rapport:1},{requiresItem:'meal_ticket',consume:'meal_ticket'}),C('問少年最近是否替學生或書店送過紙','bookstall',{insight:1},{onlyBg:'student'}),C('先幫著搬一小段貨，再順口問那批廢紙','uniform',{rapport:1},{onlyBg:'worker'}),C('問對方有沒有留下郵務或公家單據','uniform',{knowledge:1},{onlyBg:'clerk'}),C('分開問「穿什麼」與「實際做了什麼」，避免讓傳聞互相污染','uniform',{insight:1},{onlyBg:'reporter'}),C('先和替家裡跑腿的孩子聊學校，再問昨天的事','uniform',{rapport:1},{onlyBg:'teacher'}),C('先和熟悉的攤販聊幾句進貨與廢紙行情','uniform',{rapport:1},{onlyBg:'merchant'}),C('只問可確認的外觀與行為，不問少年猜對方是誰','uniform',{composure:1},{onlyBg:'veteran'}),C('從街坊閒談中拼出那人的去向','uniform',{insight:1},{onlyBg:'homemaker'})]),
uniform:S('第四章・市場','臺北・市場','1958 年 9 月','也許只是例行',['少年記起那名詢問者穿的是郵務制服，而且一路在找一封寄錯地址的信。','這不能證明完全沒有風險，但至少讓一個可怕的猜測少了幾分根據。'],[C('安心一些，去舊書攤','bookstall',{composure:1,suspicion:-1}),C('請他描述信封特徵，確認是不是同一件事','postal_check',{insight:1},{onlyBg:'reporter'}),C('問有沒有留下錯投存根','postal_check',{knowledge:1},{onlyBg:'clerk'})]),
postal_check:S('第四章・市場','臺北・市場','1958 年 9 月','一張普通存根',['少年翻出一張被拿來墊桌腳的郵件存根。上面的地址與阿川無關，日期也對得上。','它不能證明所有疑慮都是多餘的，但至少這名郵務人員有一個可被驗證的普通理由出現在市場。'],[C('收下存根作為已查證線索，去舊書攤','bookstall',{composure:1,suspicion:-1},{give:'postal_stub'})]),
bookstall:S('第五章・失而復得','臺北・舊書攤','1958 年 9 月','三頁紙',['老闆從一本缺頁字典裡抽出三張折好的紙。他覺得不像普通廢紙，便先收了起來。','失頁找回來了。真正的問題從「在哪裡」變成「該怎麼處理」。'],[C('把三頁完整交還阿川','archive',{rep:1},{give:'archive_pages'}),C('提出匿名化後再保存','redact',{knowledge:1},{requires:{knowledge:3},give:'archive_pages'}),C('請可信任的學者協助判斷','professor',{suspicion:1},{give:'archive_pages'}),C('先比對書目、頁碼與阿川剩餘筆記','redact',{knowledge:1},{onlyBg:'student',give:'archive_pages'}),C('先問紙上提到的工廠是否還能辨認出受訪者','factory_branch',{rapport:1},{onlyBg:'worker',give:'archive_pages'}),C('先替三頁加上來源、日期與接觸紀錄','professor',{knowledge:1},{onlyBg:'clerk',give:'archive_pages'}),C('先問老闆還有誰看過內容，建立接觸鏈','professor',{insight:1},{onlyBg:'reporter',give:'archive_pages'}),C('先判斷哪些內容若被學生讀到最容易脫離上下文','professor',{knowledge:1},{onlyBg:'teacher',give:'archive_pages'}),C('先把「紙的價值」和「內容的風險」分開處理','archive',{composure:1},{onlyBg:'merchant',give:'archive_pages'}),C('先確認沒有其他人正在急著追索這三頁','archive',{composure:1},{onlyBg:'veteran',give:'archive_pages'}),C('先找出紙上所有家庭地址與親屬稱謂','redact',{rapport:1},{onlyBg:'homemaker',give:'archive_pages'})]),
professor:S('第六章・保存','臺北・教授宿舍','1958 年 10 月','保存也是責任',['教授沒有評論立場，只指出最危險的是能辨認受訪者的細節。','他建議把姓名、單位與可追溯資訊分離。保存不是把一切原封不動留下，而是對未來與當事人同時負責。'],[C('採用匿名封存方案','archive',{rep:2,suspicion:-1}),C('暫時不保留可辨認資料',null,{composure:2},{ending:'people'}),C('把資料來源分級，另外留下查證紀錄','archive',{knowledge:1},{onlyBg:'student'}),C('要求所有工廠訪談先徵詢本人是否同意留存','factory_branch',{rapport:1},{onlyBg:'worker'}),C('建立一份不含姓名的索引表','archive',{knowledge:1},{onlyBg:'clerk'}),C('把來源保護與事實查證分成兩套記錄','archive',{insight:1},{onlyBg:'reporter'}),C('把「未來如何解讀」也寫進保存規則','archive',{knowledge:1},{onlyBg:'teacher'}),C('把可辨識資料分開保管，降低單點風險','archive',{composure:1},{onlyBg:'merchant'}),C('先按最壞情況檢查哪些資訊其實沒有必要保留','redact',{composure:1},{onlyBg:'veteran'}),C('優先刪除家庭地址、親屬與同住者資訊','redact',{rapport:1},{onlyBg:'homemaker'})]),
archive:S('第六章・封存','臺北・茶行','1958 年 10 月','完整，卻不公開',['阿川同意不再複製資料，先將內容封存。美惠負責整理日期，周老闆提供乾燥的木箱。','事情沒有因此結束。你開始意識到，這些紀錄背後還有更多人的故事。'],[C('完成第一批封存，繼續追查工廠訪談','factory_branch',{rep:1}),C('在這裡停下',null,{composure:1},{ending:'sealed'})]),
redact:S('第六章・去名','臺北・印刷行','1958 年 10 月','留下事情，不留下名字',['你們把姓名、地址、單位與可追溯線索分開，只留下事件、日期與感受。','阿川第一次承認：「真實」不一定等於「全部留下」。'],[C('完成匿名紀錄並繼續調查工廠訪談','factory_branch',{rep:2,composure:1}),C('完成後就此收手',null,{rep:1},{ending:'careful'})]),
factory_branch:S('第七章・機器聲','臺北・近郊紡織廠','1958 年 10 月','筆記裡的名字',['失頁中的一段訪談提到一名女工「秋月」。她談的不是政治，而是夜班、工傷與家中弟妹的學費。','你循著線索來到工廠附近，卻發現她已數日沒有上班。工友只說：「家裡出了事。」'],[C('先和工友建立信任','factory_friend',{rapport:1}),C('直接去秋月留下的地址','qiuyue_home',{stress:1}),C('先問夜班與薪資紀錄，理解她那段訪談的背景','factory_friend',{knowledge:1},{onlyBg:'student'}),C('以工作經驗和工友聊起輪班','factory_friend',{composure:1,rapport:1},{onlyBg:'worker'}),C('查看請假與出勤紀錄是否能證實她只是暫時離職','factory_friend',{knowledge:1},{onlyBg:'clerk'}),C('明說你不會引用任何人未同意公開的話','factory_friend',{rapport:1},{onlyBg:'reporter'}),C('以教師身分詢問弟妹是否需要協助','factory_friend',{rapport:1},{onlyBg:'teacher'}),C('從貨運與班次變化判斷工廠最近是否普遍缺工','factory_friend',{insight:1},{onlyBg:'merchant'}),C('先排除她的缺勤與外部局勢有直接關聯','factory_friend',{composure:1},{onlyBg:'veteran'}),C('先問她家裡是否有人能照顧病人，再決定要不要登門','factory_friend',{rapport:1},{onlyBg:'homemaker'})]),
factory_friend:S('第七章・機器聲','臺北・工廠外','1958 年 10 月','沒有人只活在一條線裡',['工友告訴你，秋月的父親病倒，她暫時回家照顧。她曾擔心自己在訪談裡說得太多，希望阿川不要留下真名。','這讓「保存紀錄」第一次變成一個具體的人，而不是抽象原則。'],[C('去秋月家，先徵詢她本人','qiuyue_home',{rep:1}),C('不打擾她，回去刪除可辨識資料',null,{composure:2},{ending:'consent'}),C('請工友代為傳話，讓秋月決定是否願意見面','qiuyue_home',{rapport:1},{onlyBg:'worker'}),C('先詢問弟妹的學校狀況，再由熟人轉達','qiuyue_home',{rapport:1},{onlyBg:'teacher'}),C('先從鄰里確認她家目前是否適合接待訪客','qiuyue_home',{rapport:1},{onlyBg:'homemaker'})]),
qiuyue_home:S('第八章・門內','臺北・萬華','1958 年 10 月','秋月的選擇',['秋月對你的到來很戒備。當你說明阿川的筆記，她沉默許久。','她沒有要求全部銷毀，只說：「我的名字不要留。但如果以後有人想知道我們怎麼過日子，其他的可以留下。」'],[C('尊重她的條件，回去重新整理','night_archive',{rep:2,knowledge:1}),C('認為風險太高，整段訪談都不保留',null,{composure:2},{ending:'people'}),C('把她的條件一條條記下，讓她自己確認','night_archive',{knowledge:1},{onlyBg:'student'}),C('告訴她工友只說了必要資訊，沒有替她補故事','night_archive',{rapport:1},{onlyBg:'worker'}),C('把「不得留真名」寫成明確的保存條件','night_archive',{knowledge:1},{onlyBg:'clerk'}),C('主動提出：沒有她同意，不把今天的談話寫進任何報導','night_archive',{rapport:1,suspicion:-1},{onlyBg:'reporter'}),C('先談弟妹與學校，讓她決定哪些家庭內容完全不要記','night_archive',{rapport:1},{onlyBg:'teacher'}),C('從帳單看出家庭壓力，但不追問她不願談的部分','night_archive',{composure:1},{onlyBg:'merchant',give:'family_note'}),C('不催促她填滿沉默，只確認最必要的界線','night_archive',{composure:1},{onlyBg:'veteran'}),C('先問哪些家人完全不希望被提到','night_archive',{rapport:1},{onlyBg:'homemaker'})]),
night_archive:S('第九章・夜間檔案','臺北・印刷行','1958 年 11 月','新的方法',['你們建立了一套規則：受訪者可以決定是否留名；敏感身分資料與內容分開；每份紀錄標明來源可信程度。','阿川原本只想「把東西留下」，現在這件事逐漸成為一項更漫長的工作。窗外，冬天快到了。'],[C('接受長期協助整理口述紀錄',null,{rep:3},{ending:'archivist'}),C('把方法交給阿川，回到自己的生活',null,{composure:2},{ending:'return'})])
};
const endings={quiet:{title:'結局：保持距離',text:'你選擇不再介入。這不是勇敢或懦弱的簡單分類，而是你為自己劃出的界線。'},careful:{title:'結局：無名的檔案',text:'事件被留下，名字則被謹慎移除。多年後，它也許會成為理解那個年代的一小塊拼圖。'},people:{title:'結局：人比紙重要',text:'你選擇優先降低當事人的風險。有些細節因此消失，而你接受歷史保存從來沒有完美答案。'},sealed:{title:'結局：封存的記憶',text:'第一批資料被完整但低調地封存。你不知道它何時重新被打開，但至少它沒有完全消失。'},consent:{title:'結局：未被打擾的人',text:'你沒有把秋月變成故事素材，而是依她曾表達的顧慮移除可辨識資訊。保存開始有了界線。'},archivist:{title:'結局：霧中的記錄者',text:'你沒有成為英雄。接下來的日子裡，你只是反覆確認、整理、去名、詢問同意。普通人的生活因此多了一點被留下的可能。'},return:{title:'結局：把方法留下',text:'你離開整理工作，但你們建立的方法被保留下來。阿川終於明白，記錄不是占有別人的故事。'}};
const $=id=>document.getElementById(id);const el={startScreen:$('startScreen'),gameScreen:$('gameScreen'),endingScreen:$('endingScreen'),nameInput:$('nameInput'),backgroundChoices:$('backgroundChoices'),startBtn:$('startBtn'),loadStartBtn:$('loadStartBtn'),playerName:$('playerName'),playerBg:$('playerBg'),passiveName:$('passiveName'),stress:$('stress'),rep:$('rep'),suspicion:$('suspicion'),attributeBar:$('attributeBar'),chapter:$('chapter'),location:$('location'),sceneDate:$('sceneDate'),sceneTitle:$('sceneTitle'),sceneText:$('sceneText'),choices:$('choices'),saveBtn:$('saveBtn'),inventoryBtn:$('inventoryBtn'),logBtn:$('logBtn'),restartBtn:$('restartBtn'),inventoryPanel:$('inventoryPanel'),inventoryList:$('inventoryList'),equipmentList:$('equipmentList'),closeInventoryBtn:$('closeInventoryBtn'),logPanel:$('logPanel'),logList:$('logList'),closeLogBtn:$('closeLogBtn'),endingTitle:$('endingTitle'),endingText:$('endingText'),endingStats:$('endingStats'),againBtn:$('againBtn'),menuBtn:$('menuBtn'),menu:$('menu'),menuClose:$('menuClose'),menuSave:$('menuSave'),menuLoad:$('menuLoad'),menuRestart:$('menuRestart'),backdrop:$('backdrop'),toast:$('toast')};let selectedBg=null,state=null,timer=null;
function newState(name,bg){const r=roles[bg];return{version:4,name:name.trim()||'無名旅人',bg,scene:'intro',stress:0,rep:0,suspicion:0,attributes:{...r.stats},inventory:[...r.items],equipment:{},visited:[],log:[{title:'故事開始',text:`1958 年 9 月，你以${r.label}的身分收到一封沒有署名的信。`}],finished:false}}
const clamp=(n,min=0,max=99)=>Math.max(min,Math.min(max,n));
function effects(e={}){const c=[];for(const k of ['stress','rep','suspicion'])if(typeof e[k]==='number'){let delta=e[k];if(k==='stress'&&delta>0&&state.bg==='veteran')delta=Math.max(0,delta-1);state[k]=clamp(state[k]+delta);if(delta)c.push(`${{stress:'壓力',rep:'聲望',suspicion:'疑心'}[k]} ${delta>0?'+':''}${delta}`)}for(const k of ['insight','knowledge','composure','rapport'])if(typeof e[k]==='number'){const delta=e[k];state.attributes[k]=clamp(state.attributes[k]+delta,0,20);if(delta)c.push(`${{insight:'觀察',knowledge:'知識',composure:'沉著',rapport:'人情'}[k]} ${delta>0?'+':''}${delta}`)}return c}
function requirement(c){if(c.onlyBg&&c.onlyBg!==state.bg)return false;if(c.requiresItem&&!state.inventory.includes(c.requiresItem))return false;return Object.entries(c.requires||{}).every(([k,v])=>(k in state.attributes?state.attributes[k]:state[k])>=v)}function esc(v){return String(v).replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]))}function toast(m){clearTimeout(timer);el.toast.textContent=m;el.toast.classList.add('show');timer=setTimeout(()=>el.toast.classList.remove('show'),2300)}
function renderStatus(){const r=roles[state.bg]||roles.student;el.playerName.textContent=state.name;el.playerBg.textContent=r.label;el.passiveName.textContent=r.passive;el.stress.textContent=state.stress;el.rep.textContent=state.rep;el.suspicion.textContent=state.suspicion;el.attributeBar.innerHTML=`<span>觀察 <b>${state.attributes.insight}</b></span><span>知識 <b>${state.attributes.knowledge}</b></span><span>沉著 <b>${state.attributes.composure}</b></span><span>人情 <b>${state.attributes.rapport}</b></span>`}
function renderScene(){const s=scenes[state.scene];if(!s)return toast('找不到場景');showScreen('game');renderStatus();el.chapter.textContent=s.chapter;el.location.textContent=s.location;el.sceneDate.textContent=s.date;el.sceneTitle.textContent=s.title;const paras=s.text.map(p=>`<p>${esc(p)}</p>`);const extra=passiveText[state.scene]?.[state.bg];if(extra)paras.push(`<p class="identity-text"><b>${esc(roles[state.bg].passive)}</b>｜${esc(extra)}</p>`);el.sceneText.innerHTML=paras.join('');el.choices.innerHTML='';s.choices.filter(c=>!c.onlyBg||c.onlyBg===state.bg).forEach(c=>{const ok=requirement(c),b=document.createElement('button');b.className='choice-btn'+(ok?'':' locked');b.disabled=!ok;let locked='';if(!ok)locked=c.requiresItem?`需要道具：${items[c.requiresItem]?.name||'未知道具'}`:'目前條件不足';b.innerHTML=`<strong>${esc(c.label)}</strong>${locked?`<small>${esc(locked)}</small>`:''}`;b.onclick=()=>choose(c);el.choices.appendChild(b)});window.scrollTo({top:0,behavior:'smooth'})}
function give(id,notes){if(id&&!state.inventory.includes(id)){state.inventory.push(id);if(notes)notes.push(`獲得 ${items[id]?.name||id}`)}}function choose(c){if(!requirement(c))return;const notes=[];const ch=effects(c.effects);if(c.give)give(c.give,notes);if(c.consume&&state.inventory.includes(c.consume)){state.inventory=state.inventory.filter(x=>x!==c.consume);notes.push(`使用 ${items[c.consume]?.name||c.consume}`)}if(ch.length)notes.push(ch.join('・'));if(notes.length)toast(notes.join('｜'));state.log.unshift({title:scenes[state.scene].title,text:`你選擇了「${c.label}」。`});if(c.ending)return finish(c.ending);state.scene=c.next;autoSave();renderScene()}
function equip(id){const it=items[id];if(!it||it.type!=='equipment')return;const old=state.equipment[it.slot];if(old===id){delete state.equipment[it.slot];effects(Object.fromEntries(Object.entries(it.bonus||{}).map(([k,v])=>[k,-v])));toast(`卸下：${it.name}`)}else{if(old){const oi=items[old];effects(Object.fromEntries(Object.entries(oi?.bonus||{}).map(([k,v])=>[k,-v])))}state.equipment[it.slot]=id;effects(it.bonus);toast(`裝備：${it.name}`)}renderStatus();renderInventory();autoSave()}
function renderInventory(){const r=roles[state.bg],eq=Object.values(state.equipment);el.equipmentList.innerHTML=`<div class="equipment-box"><strong>被動｜${esc(r.passive)}</strong><br><small>${esc(r.desc)}</small><br><small>${eq.length?'裝備：'+eq.map(x=>items[x]?.name||x).join('・'):'尚未裝備任何物品'}</small></div>`;el.inventoryList.innerHTML=state.inventory.map(id=>{const i=items[id];if(!i)return'';const equipped=Object.values(state.equipment).includes(id);return `<div class="item-card"><strong>${esc(i.name)}</strong><small>${esc(i.desc)}</small>${i.type==='equipment'?`<button class="item-btn" data-equip="${id}">${equipped?'卸下':'裝備'}</button>`:''}</div>`}).join('')||'<div class="item-card">行囊是空的。</div>';el.inventoryList.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.equip))}
function finish(id){const e=endings[id];state.finished=true;state.ending=id;autoSave();showScreen('ending');el.endingTitle.textContent=e.title;el.endingText.textContent=e.text;el.endingStats.innerHTML=`<span>壓力<b>${state.stress}</b></span><span>聲望<b>${state.rep}</b></span><span>疑心<b>${state.suspicion}</b></span>`;window.scrollTo({top:0,behavior:'smooth'})}function renderLog(){el.logList.innerHTML=state.log.map(x=>`<div class="log-entry"><b>${esc(x.title)}</b><br>${esc(x.text)}</div>`).join('')}function autoSave(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(_){}}function save(){if(!state)return toast('沒有可保存的進度');autoSave();toast('進度已保存在此裝置')}
function migrate(s){if(!s)return null;if(!roles[s.bg])s.bg='student';s.version=4;s.inventory=(s.inventory||[]).filter(id=>items[id]);s.equipment=s.equipment||{};s.attributes=s.attributes||{...roles[s.bg].stats};s.log=s.log||[];return s}function load(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw)for(const k of OLD_KEYS){raw=localStorage.getItem(k);if(raw)break}state=migrate(raw?JSON.parse(raw):null)}catch(_){state=null}if(!state)return toast('找不到存檔');autoSave();closeMenu();state.finished?finish(state.ending):renderScene();toast('已讀取存檔')}
function restart(){if(!confirm('要放棄目前進度並回到開始畫面嗎？'))return;state=null;selectedBg=null;el.nameInput.value='';[...el.backgroundChoices.querySelectorAll('.bg-choice')].forEach(b=>b.classList.remove('selected'));el.startBtn.disabled=true;closeMenu();showScreen('start')}function showScreen(w){el.startScreen.classList.toggle('hidden',w!=='start');el.gameScreen.classList.toggle('hidden',w!=='game');el.endingScreen.classList.toggle('hidden',w!=='ending')}function openMenu(){el.menu.classList.remove('hidden');el.backdrop.classList.remove('hidden')}function closeMenu(){el.menu.classList.add('hidden');el.backdrop.classList.add('hidden')}
el.backgroundChoices.onclick=e=>{const b=e.target.closest('.bg-choice');if(!b)return;selectedBg=b.dataset.bg;[...el.backgroundChoices.querySelectorAll('.bg-choice')].forEach(x=>x.classList.toggle('selected',x===b));el.startBtn.disabled=false};el.startBtn.onclick=()=>{state=newState(el.nameInput.value,selectedBg);autoSave();renderScene()};el.loadStartBtn.onclick=load;el.saveBtn.onclick=save;el.inventoryBtn.onclick=()=>{renderInventory();el.inventoryPanel.classList.toggle('hidden');el.logPanel.classList.add('hidden')};el.closeInventoryBtn.onclick=()=>el.inventoryPanel.classList.add('hidden');el.logBtn.onclick=()=>{renderLog();el.logPanel.classList.toggle('hidden');el.inventoryPanel.classList.add('hidden')};el.closeLogBtn.onclick=()=>el.logPanel.classList.add('hidden');el.restartBtn.onclick=restart;el.againBtn.onclick=restart;el.menuBtn.onclick=openMenu;el.menuClose.onclick=closeMenu;el.backdrop.onclick=closeMenu;el.menuSave.onclick=save;el.menuLoad.onclick=load;el.menuRestart.onclick=restart;
})();